import assert from 'node:assert/strict';
import fs from 'node:fs';

const p='loterias-ai/edge-live/evidence/betfair-spain-sporting-legends-overdue-first-bet-p0-v1.json';
const d=JSON.parse(fs.readFileSync(p,'utf8'));

assert.equal(d.market,'ES');
assert.equal(d.sourceType,'ONLINE');
assert.equal(d.promotion,false);
assert.equal(d.breakthrough.currentBetfairSpainRuleVerified,true);
assert.equal(d.breakthrough.providerRuleCorroborated,true);
assert.equal(d.breakthrough.semanticCorrection,'FOLLOWING_DAY_BOUNDARY_IS_THE_VERIFIED_DAILY_GUARANTEED_HIT_TIME');
assert.equal(d.providerBoundaryEvidence.dailyExampleGuaranteedHitTime,1513123200);
assert.equal(d.providerBoundaryEvidence.dailyExampleGuaranteedHitTimeUtc,'2017-12-13T00:00:00Z');
assert.equal(d.providerBoundaryEvidence.weeklyExampleGuaranteedHitTime,1513555200);
assert.equal(d.providerBoundaryEvidence.weeklyExampleGuaranteedHitTimeUtc,'2017-12-18T00:00:00Z');
assert.equal(d.providerBoundaryEvidence.providerGuaranteedHitTimeDefinesFollowingDayBoundaryVerified,true);
assert.equal(d.clockSemantics.earlyRetriggerCutoffIsExecutableDeadline,false);
assert.equal(d.clockSemantics.onlyCurrentTickerGuaranteedHitTimeMayDefineCurrentExecutableBoundary,true);
assert.equal(d.clockSemantics.currentTickerGuaranteedHitTimeRecovered,false);
assert.equal(d.tickerProtocolProof.gamedataWinCountAttribute,'winc');
assert.equal(d.tickerProtocolProof.amountWinsIsNotWinCount,true);
assert.equal(d.tickerProtocolProof.parserVersionRequired,'playtech-mhb-ticker-parser-v1.6-win-count-timestamps');
assert.equal(d.tickerProtocolProof.detectorVersionRequired,'sporting-legends-overdue-first-bet-v1.2-guaranteed-hit-boundary');
assert.equal(d.economicRoute.exactServedRtpVariantRequiredForThisRoute,false);
assert.equal(d.economicRoute.powerPlayWeightingRequiredForThisRoute,false);
assert.equal(d.economicRoute.normalRandomHazardFunctionRequiredForThisSpecialRoute,false);
assert.equal(d.economicRoute.networkFirstBetRaceProbabilityRequired,true);
assert.equal(d.raceBound.usableForExecutionNow,false);
assert.equal(d.gateProgress.closed,7);
assert.equal(d.gateProgress.total,18);
assert.equal(d.execution.decision,'NO_PLAY');
assert.equal(d.execution.realMoneyAllowed,false);
assert.equal(d.execution.realStakeEUR,0);
assert.equal(d.execution.maxSpins,0);
assert.equal(d.execution.maxTotalStakeEUR,0);
assert.equal(d.hardGuards.noRaceAutomation,true);
assert.equal(d.hardGuards.providerExampleTimestampCannotPopulateCurrentBetfairGuaranteedHitTime,true);
assert.equal(d.hardGuards.followingDayRuleDoesNotProveOurBetWillBeFirst,true);
assert.equal(d.hardGuards.poissonStationarityCannotBeAssumed,true);

console.log('betfair-spain-sporting-legends-overdue-first-bet-p0-v1.test.mjs: PASS');
