import assert from 'node:assert/strict';
import fs from 'node:fs';
const d=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/betfair-spain-apmccoy-powerplay-jackpot-eligibility-v1.json','utf8'));
assert.equal(d.market,'ES');
assert.equal(d.operator,'Betfair Spain');
assert.equal(d.sourceType,'ONLINE');
assert.equal(d.promotion,false);
assert.equal(d.closedSemantics.powerPlayExistsInExactBetfairSpainBuild,true);
assert.equal(d.closedSemantics.sportingJackpotsCanTriggerDuringPowerPlayInExactBetfairSpainBuild,true);
assert.equal(d.closedSemantics.providerStatesJackpotsCanTriggerOnAnySpin,true);
assert.equal(d.stillUnknown.exactJackpotStakeWeightingDuringPowerPlayVerified,false);
assert.equal(d.stillUnknown.superSpinJackpotEligibilityVerified,false);
assert.equal(d.economicGuard.nominalHurdleUsableForExecution,false);
assert.equal(d.execution.decision,'NO_PLAY');
assert.equal(d.execution.realMoneyAllowed,false);
assert.equal(d.hardGuards.anySpinDoesNotMeanEqualProbabilityPerSpin,true);
assert.equal(d.hardGuards.fiveSpinBundleDoesNotMeanFiveTimesHazard,true);
assert.equal(d.hardGuards.costMultipleDoesNotEqualJackpotHazardWeight,true);
console.log('betfair-spain-apmccoy-powerplay-jackpot-eligibility-v1.test.mjs: PASS');
