import assert from 'node:assert/strict';
import fs from 'node:fs';
const d=JSON.parse(fs.readFileSync('/tmp/edgework/betfair-spain-sporting-legends-overdue-first-bet-p0-v1.json','utf8'));
assert.equal(d.market,'ES');
assert.equal(d.sourceType,'ONLINE');
assert.equal(d.promotion,false);
assert.equal(d.breakthrough.currentBetfairSpainRuleVerified,true);
assert.equal(d.clockSemantics.earlyRetriggerCutoffIsDeadline,false);
assert.equal(d.clockSemantics.onlyCurrentTickerGuaranteedHitTimeMayDefineExecutableDeadline,true);
assert.equal(d.tickerProtocolProof.gamedataWinCountAttribute,'winc');
assert.equal(d.tickerProtocolProof.amountWinsIsNotWinCount,true);
assert.equal(d.economicRoute.exactServedRtpVariantRequiredForThisRoute,false);
assert.equal(d.economicRoute.powerPlayWeightingRequiredForThisRoute,false);
assert.equal(d.economicRoute.normalRandomHazardFunctionRequiredForThisRoute,false);
assert.equal(d.gateProgress.closed,5);
assert.equal(d.gateProgress.total,14);
assert.equal(d.execution.decision,'NO_PLAY');
assert.equal(d.execution.realMoneyAllowed,false);
assert.equal(d.execution.realStakeEUR,0);
assert.equal(d.execution.maxSpins,0);
assert.equal(d.hardGuards.noRaceAutomation,true);
assert.equal(d.hardGuards.overdueRuleDoesNotProveOurBetWillBeFirst,true);
console.log('betfair-spain-sporting-legends-overdue-first-bet-p0-v1.test.mjs: PASS');
