import assert from 'node:assert/strict';
import fs from 'node:fs';
const p='loterias-ai/edge-live/evidence/betfair-spain-apmccoy-visual-final-green-route-v1.json';
const d=JSON.parse(fs.readFileSync(p,'utf8'));
assert.equal(d.market,'ES');
assert.equal(d.sourceType,'ONLINE');
assert.equal(d.promotion,false);
assert.equal(d.route.visualOnlyGreenDisabled,true);
assert.equal(d.route.finalTickerRequiredForThisRoute,true);
assert.equal(d.route.exactServerTickerImsOverdueRecheckRequiredForGreen,true);
assert.equal(d.route.priorValidatedVisualRaceLedgerRequired,true);
assert.equal(d.route.currentRecheckScreenshotsRequired,2);
assert.equal(d.route.maxDetectionAgeSeconds,2);
assert.equal(d.route.greenMaxSpins,0);
assert.equal(d.scientificCorrection.falseGreenPathClosed,true);
assert.equal(d.currentLiveState.greenNow,false);
assert.equal(d.execution.decision,'NO_PLAY');
assert.equal(d.execution.realMoneyAllowed,false);
assert.equal(d.execution.realStakeEUR,0);
assert.equal(d.hardGuards.visualEvidenceCannotProveUnawardedServerState,true);
assert.equal(d.hardGuards.exactTickerImsRequiredForGreen,true);
assert.equal(d.hardGuards.noAutomaticWagering,true);
console.log('betfair-spain-apmccoy-visual-final-green-route-v1.test.mjs: PASS');
