import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const script='loterias-ai/edge-live/progressive-score-research-v1.mjs';
const output='loterias-ai/edge-live/evidence/progressive-score-research-v1.json';
execFileSync(process.execPath,[script],{stdio:'pipe'});
const data=JSON.parse(fs.readFileSync(output,'utf8'));
const row=(data.rows||[]).find(x=>x?.id==='botemania-diamond-bonanza-25c');
assert.ok(row);
assert.equal(data.version,'progressive-score-research-v1.5-no-mixed-source-arithmetic');
assert.equal(data.guards?.noMixedSourceRtpContributionArithmetic,true);
const r=row.researchScenario;
assert.equal(r?.economicInputsComposable,false);
assert.equal(r?.baseRtpExcludingJackpotPct,null);
assert.equal(r?.averageJackpotContributionPct,null);
assert.equal(r?.estimatedRtpPct,null);
assert.equal(r?.breakEvenScore,null);
assert.equal(r?.breakEvenJackpotNominal,null);
assert.equal(r?.distanceToResearchThresholdNominal,null);
assert.equal(r?.nominalZone,'NO_VERIFIED_RESEARCH_THRESHOLD');
assert.equal(r?.nominalNearOrAbove,false);
assert.equal(r?.operationalThresholdComparable,false);
assert.equal(r?.countsAsNearOrAboveResearchThreshold,false);
assert.equal(r?.legacyExternalInputs?.roxorPublishedRtpPct,93.52);
assert.equal(r?.legacyExternalInputs?.ballyJackpotContributionPct,5.66);
assert.equal(r?.legacyExternalInputs?.historicalGamesysSeedGBP,500);
assert.equal(r?.legacyExternalInputs?.historicalGamesysAverageHitGBP,7309);
assert.equal((data.nearResearchThreshold||[]).some(x=>x?.id==='botemania-diamond-bonanza-25c'),false);
console.log('diamond-comparator-integrity-v1.test.mjs: ok');
