import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/jpk-spain-disclosure-taxonomy-v1.json','utf8'));
assert.equal(e.status,'RESEARCH_ONLY_NO_PLAY');
assert.equal(e.realMoneyAllowed,false);
assert.ok(e.cleanDecompositions.length>=6);
const fortune=e.cleanDecompositions.find(x=>x.game==='Mega Bars Fortune Wheel: Jackpot King');
const mega=e.cleanDecompositions.find(x=>x.game==='Mega Bars: Jackpot King');
assert.ok(fortune&&mega);
assert.equal(fortune.baseRtp,0.955);
assert.equal(mega.baseRtp,0.955);
assert.equal(fortune.visibleEntrySymbols,5);
assert.equal(mega.visibleEntrySymbols,5);
assert.equal(fortune.jackpotFunding,0.0038);
assert.equal(fortune.reserveFunding,0.0011);
assert.equal(mega.jackpotFunding,0.0086);
assert.equal(mega.reserveFunding,0.0013);
assert.equal(e.sameFamilyControlledComparison.sameBaseRtp,true);
assert.equal(e.sameFamilyControlledComparison.sameVisibleEntryCount,true);
assert.equal(e.sameFamilyControlledComparison.sharedJackpotKingPool,true);
assert.equal(e.sameFamilyControlledComparison.sameFundingProfile,false);
assert.equal(e.baseRtpScreen.highestCleanBaseRtp,0.955);
assert.equal(e.baseRtpScreen.coLeaders.length,2);
assert.equal(e.baseRtpScreen.notAPlaySignal,true);
const pig=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='The Pig Wizard: Jackpot King');
assert.ok(pig);
assert.equal(pig.safeToAddFundingToBaseAsRtp,false);
const wish=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='Wish Upon a Leprechaun: Jackpot King');
assert.ok(wish);
assert.equal(wish.safeForExecutionFingerprint,false);
const slots=e.ambiguousOrLegacyDisclosures.find(x=>x.game==="Slots O' Gold: Jackpot King");
assert.ok(slots);
assert.equal(slots.safeForSpainSeedInference,false);
assert.equal(e.execution.decision,'NO_PLAY');
for(const key of ['identityVerified','thresholdVerified','stakeVerified','strategyVerified','rulesFingerprintVerified','prospectiveValidationPassed']) assert.equal(e.execution[key],false);
assert.equal(e.hardGuards.fundingIsNotHazard,true);
assert.equal(e.hardGuards.fundingIsNotRtpUnlessExplicitlyProven,true);
assert.equal(e.hardGuards.sameBaseSameTriggerSamePoolIsNotSameFunding,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

console.log('edge-jpk-spain-disclosure-taxonomy-v1.test.mjs: PASS');
