import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/jpk-spain-base-return-corroboration-v1.json','utf8'));
assert.equal(e.status,'RESEARCH_ONLY_NO_PLAY');
assert.equal(e.realMoneyAllowed,false);
assert.equal(e.bet365SpainRegulatoryDisclosure.regulatorySemantics.pageStatesJackpotAssignedAmountsExcludedFromTheseCalculations,true);
assert.equal(e.bet365SpainRegulatoryDisclosure.regulatorySemantics.semanticAmbiguityDetectedByCrossTitleControls,true);
assert.equal(e.exactTitleComparisons.length,4);
assert.equal(e.matrixAssessment.exactNumericBaseMatches,2);
assert.equal(e.matrixAssessment.exactTitleMismatches,2);
assert.equal(e.matrixAssessment.generalCrossOperatorBaseRtpTransferAllowed,false);
assert.equal(e.matrixAssessment.generalCrossOperatorRtpDecompositionTransferAllowed,false);
for(const row of e.exactTitleComparisons){
  assert.equal(row.assessment.exactTitleFamilyMatch,true);
  assert.equal(row.assessment.exactConfigurationEquivalent,false);
  assert.equal(row.assessment.hazardEquivalent,false);
  assert.equal(row.assessment.executionEligible,false);
  assert.equal(row.bet365.actualReturnByMonth.length,6);
}
const eye=e.exactTitleComparisons.find(x=>x.title==='Eye Of Horus Jackpot King');
assert.ok(eye);
assert.equal(eye.bet365.theoreticalRtp,0.9546);
assert.equal(eye.botemania.baseRtp,0.9546);
assert.equal(eye.assessment.exactTheoreticalToBotemaniaBaseNumericMatch,true);
assert.equal(eye.botemania.contributionConflict.resolved,false);
const mega=e.exactTitleComparisons.find(x=>x.title==='Eye of Horus Megaways Jackpot King');
assert.ok(mega);
assert.equal(mega.bet365.theoreticalRtp,0.945);
assert.equal(mega.botemania.baseRtp,0.945);
assert.equal(mega.assessment.exactTheoreticalToBotemaniaBaseNumericMatch,true);
const ted=e.exactTitleComparisons.find(x=>x.title==='Ted Jackpot King');
assert.ok(ted);
assert.equal(ted.bet365.theoreticalRtp,0.9304);
assert.equal(ted.botemania.baseRtp,0.9302);
assert.equal(ted.assessment.exactTheoreticalToBotemaniaBaseNumericMatch,false);
assert.equal(ted.assessment.configurationDriftOrVariantCannotBeExcluded,true);
const goonies=e.exactTitleComparisons.find(x=>x.title==='The Goonies Return Jackpot King');
assert.ok(goonies);
assert.equal(goonies.bet365.theoreticalRtp,0.9355);
assert.equal(goonies.botemania.baseRtp,0.9306);
assert.equal(goonies.botemania.publishedBasePlusFundingComponents,0.9355);
assert.equal(goonies.assessment.bet365TheoreticalNumericallyEqualsBotemaniaBasePlusFundingComponents,true);
assert.equal(goonies.assessment.semanticEquivalenceOfThe9355FigureProven,false);
assert.equal(e.execution.decision,'NO_PLAY');
for(const key of ['identityVerified','thresholdVerified','stakeVerified','strategyVerified','rulesFingerprintVerified','prospectiveValidationPassed'])assert.equal(e.execution[key],false);
assert.equal(e.hardGuards.sameTitleIsNotConfigurationEquivalence,true);
assert.equal(e.hardGuards.sameNumericRtpIsNotDecompositionEquivalence,true);
assert.equal(e.hardGuards.crossOperatorTheoreticalRtpCannotBeTransferredWithoutFingerprint,true);
assert.equal(e.hardGuards.numericSumMatchDoesNotProveSemanticComponentIdentity,true);
assert.equal(e.hardGuards.rtpComparisonDoesNotProveEqualHazard,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

console.log('edge-jpk-spain-base-return-corroboration-v1.test.mjs: PASS');
