import assert from 'node:assert/strict';
import fs from 'node:fs';

const worker=fs.readFileSync('loterias-ai/edge-backend/src/index-v18.mjs','utf8');
const refs=fs.readFileSync('loterias-ai/edge-backend/src/external-jackpot-history-references-v1.mjs','utf8');
const ui=fs.readFileSync('loterias-ai/edge-live/edge-history-depth-client-v1.mjs','utf8');
const loader=fs.readFileSync('loterias-ai/edge-live/edge-live-ux-v1.mjs','utf8');
const wrangler=fs.readFileSync('loterias-ai/edge-backend/wrangler.jsonc','utf8');
const semantics=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/jackpot-history-depth-semantics-v1.json','utf8'));
const contract=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/client-execution-contract-v1.json','utf8'));

assert.match(wrangler,/"main"\s*:\s*"src\/index-v18\.mjs"/);
assert.ok(worker.includes("edge-sentinel-v18-jackpot-history-depth-20260824a"));
assert.ok(worker.includes("path==='/science/history-depth'"));
assert.ok(worker.includes('timingSampleN:fullCycles'));
assert.ok(worker.includes('awardSampleN:verifiedAwards'));
assert.ok(worker.includes('externalWinsAreNotAddedToSpanishN:true'));
assert.ok(worker.includes('externalOverlapCannotInflateReferenceCount:true'));
assert.ok(worker.includes('externalReferenceProviderAggregateWinsNonOverlapping'));
assert.ok(worker.includes('externalRawRowsFullyIngestedIntoEdge:0'));
assert.ok(refs.includes('winsRecorded:1060'));
assert.ok(refs.includes('winsRecorded:4748'));
assert.ok(refs.includes('winsRecorded:1232'));
assert.ok(refs.includes("overlapGroup:'GAMESYS_AGGREGATE'"));
assert.ok(refs.includes('isProviderAggregate:true'));
assert.ok(refs.includes('transferAllowed:false'));
assert.ok(ui.includes('Lecturas ≠ ciclos ≠ premios'));
assert.ok(ui.includes('NO suma al n español'));
assert.ok(ui.includes('NO se vuelven a sumar'));
assert.ok(loader.includes("import './edge-history-depth-client-v1.mjs'"));
assert.equal(semantics.hardGuards.observationCountCannotMasqueradeAsWinCount,true);
assert.equal(semantics.hardGuards.externalWinsCannotIncreaseSpanishSampleN,true);
assert.equal(semantics.hardGuards.configurationIdentityRequiredBeforeParameterTransfer,true);
assert.equal(semantics.hardGuards.timingPatternRequiresProspectiveSpanishValidation,true);
assert.equal(semantics.hardGuards.realMoneyAllowed,false);
assert.equal(contract.enabled,false);
assert.equal(contract.realMoneyAllowed,false);
assert.equal(contract.scientificGatePassed,false);
console.log('edge-jackpot-history-depth-v18.test.mjs: PASS');
