import assert from 'node:assert/strict';
import fs from 'node:fs';
import { SPANISH_JACKPOT_AWARDS } from '../edge-backend/src/spanish-jackpot-awards-v1.mjs';
import { SPANISH_JACKPOT_AWARDS_V2_EXTRA } from '../edge-backend/src/spanish-jackpot-awards-v2-extra.mjs';
import { buildMillionaireGenieThresholdEnvelope } from '../edge-backend/src/millionaire-genie-threshold-envelope-v1.mjs';

const close=(a,b,tol=1e-6)=>assert.ok(Math.abs(Number(a)-Number(b))<=tol,`${a} != ${b}`);
const all=[...SPANISH_JACKPOT_AWARDS,...SPANISH_JACKPOT_AWARDS_V2_EXTRA];
const mg=all.filter(x=>x.operator==='888casino-es'&&x.game==='Millionaire Genie');
assert.equal(SPANISH_JACKPOT_AWARDS_V2_EXTRA.length,1);
assert.equal(SPANISH_JACKPOT_AWARDS_V2_EXTRA[0].amountEUR,520000);
assert.equal(SPANISH_JACKPOT_AWARDS_V2_EXTRA[0].datePrecision,'MONTH');
assert.equal(SPANISH_JACKPOT_AWARDS_V2_EXTRA[0].configurationIdentityCurrent,false);
assert.equal(mg.length,21);

const env=buildMillionaireGenieThresholdEnvelope({awardAmounts:mg.map(x=>x.amountEUR),theoreticalRtp:0.9502,contributionRates:[0.02,0.035],currentJackpotEUR:166056.12});
assert.equal(env.eligible,true);
assert.equal(env.stats.n,21);
assert.equal(env.stats.totalEUR,10235090);
close(env.stats.meanEUR,487385.2380952381);
assert.equal(env.stats.medianEUR,456184);
assert.equal(env.stats.minEUR,40000);
assert.equal(env.stats.maxEUR,1221429);
assert.equal(env.scenarios.length,4);
close(env.minimumEnumeratedThresholdEUR,636565.2816326524);
assert.equal(env.currentBelowAllEnumeratedConditionalScreens,true);
assert.equal(env.assumptionsVerified.historicalConfigurationContinuity,false);
assert.equal(env.assumptionsVerified.contributionRate,false);
assert.equal(env.assumptionsVerified.rtpSemantic,false);
assert.equal(env.assumptionsVerified.seed,false);
assert.equal(env.assumptionsVerified.constantHazard,false);
assert.equal(env.positiveEvProven,false);
assert.equal(env.negativeEvProven,false);
assert.equal(env.realMoneyAllowed,false);

const s20=env.scenarios.find(x=>x.contributionRateFraction===0.02&&x.rtpSemantic==='THEORETICAL_RTP_IS_BASE_EXCLUDING_PROGRESSIVE');
close(s20.conditionalBreakEvenJackpotEURRange[0],1113989.242857142);
close(s20.conditionalBreakEvenJackpotEURRange[1],1213589.242857142);
const s35=env.scenarios.find(x=>x.contributionRateFraction===0.035&&x.rtpSemantic==='THEORETICAL_RTP_IS_BASE_EXCLUDING_PROGRESSIVE');
close(s35.conditionalBreakEvenJackpotEURRange[0],636565.2816326524);
close(s35.conditionalBreakEvenJackpotEURRange[1],693479.5673469382);
const s35inc=env.scenarios.find(x=>x.contributionRateFraction===0.035&&x.rtpSemantic==='THEORETICAL_RTP_INCLUDES_STATIONARY_PROGRESSIVE_RETURN');
close(s35inc.conditionalBreakEvenJackpotEURRange[0],1083950.5197278908);
close(s35inc.conditionalBreakEvenJackpotEURRange[1],1180864.8054421765);

const wrangler=fs.readFileSync('loterias-ai/edge-backend/wrangler.jsonc','utf8');
const worker=fs.readFileSync('loterias-ai/edge-backend/src/index-v20.mjs','utf8');
const ui=fs.readFileSync('loterias-ai/edge-live/edge-millionaire-genie-envelope-client-v1.mjs','utf8');
const loader=fs.readFileSync('loterias-ai/edge-live/edge-live-ux-v1.mjs','utf8');
const contract=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/client-execution-contract-v1.json','utf8'));
assert.match(wrangler,/"main"\s*:\s*"src\/index-v20\.mjs"/);
assert.ok(worker.includes('edge-sentinel-v20-millionaire-genie-envelope-20260824a'));
assert.ok(worker.includes('enumeratedThresholdEnvelopeIsNotRigorousLowerBound=true')||worker.includes('enumeratedThresholdEnvelopeIsNotRigorousLowerBound=true'.replace('=',''))||worker.includes('enumeratedThresholdEnvelopeIsNotRigorousLowerBound'));
assert.ok(ui.includes('Thresholds condicionales, no ejecución'));
assert.ok(ui.includes('no demuestra -EV'));
assert.ok(loader.includes("import './edge-millionaire-genie-envelope-client-v1.mjs'"));
assert.equal(contract.enabled,false);
assert.equal(contract.realMoneyAllowed,false);
assert.equal(contract.scientificGatePassed,false);
console.log('edge-millionaire-genie-envelope-v20.test.mjs: PASS');
