import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildBreakthroughCards,cardHtml} from '../edge-live/research-breakthroughs-v1.mjs';

const sporting=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/betfair-spain-sporting-legends-ap-mccoy-p0-v1.json','utf8'));
const cards=buildBreakthroughCards(sporting);
assert.equal(cards.length,1);
const c=cards[0];
assert.equal(c.kind,'SPORTING_P0');
assert.equal(c.action,'NO_PLAY');
assert.equal(c.sourceType,'ONLINE');
assert.equal(c.promotion,false);
assert.equal(c.closedGates,5);
assert.equal(c.totalGates,12);
assert.equal(c.bestBaseRtpPct,97.17);
assert.equal(c.breakEvenAdditionalPct,2.83);
assert.equal(c.launcherVerified,true);
assert.equal(c.timedMechanicVerified,true);
assert.equal(c.tickerVerified,false);
assert.equal(c.currentDailyAmountVerified,false);
assert.equal(c.currentDeadlineVerified,false);
assert.equal(c.hazardVerified,false);
const html=cardHtml(c);
assert.match(html,/Betfair Spain · ONLINE · ESPAÑA/);
assert.match(html,/5\/12/);
assert.match(html,/97\.17%/);
assert.match(html,/2\.83%/);
assert.match(html,/POR CERRAR/);
assert.match(html,/NO ES SEÑAL DE APUESTA/);
assert.doesNotMatch(html,/JUGAR AHORA/);
console.log('edge-sporting-legends-p0-v1.test.mjs: PASS');
