import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/jpk-spain-disclosure-taxonomy-v1.json','utf8'));
assert.equal(e.status,'RESEARCH_ONLY_NO_PLAY');
assert.equal(e.realMoneyAllowed,false);
const fortune=e.cleanDecompositions.find(x=>x.game==='Mega Bars Fortune Wheel: Jackpot King');
assert.ok(fortune);
assert.equal(fortune.baseRtp,0.955);
assert.equal(fortune.visibleEntrySymbols,5);
assert.equal(fortune.jackpotFunding,0.0038);
assert.equal(fortune.reserveFunding,0.0011);
assert.equal(e.cleanDecompositions.some(x=>x.game==='Mega Bars: Jackpot King'),false);
assert.equal(e.cleanDecompositions.some(x=>x.game==='The Goonies Return: Jackpot King'),false);
const mega=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='Mega Bars: Jackpot King');
assert.ok(mega);
assert.equal(mega.classification,'INTERNAL_OPERATOR_PAGE_FUNDING_CONFLICT');
assert.equal(mega.bodyJackpotFunding,0.0232);
assert.equal(mega.bodyReserveFunding,0.0068);
assert.equal(mega.footerJackpotFunding,0.0086);
assert.equal(mega.footerReserveFunding,0.0013);
assert.equal(mega.safeFundingConfiguration,null);
assert.equal(mega.safeForExecutionFingerprint,false);
const goonies=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='The Goonies Return: Jackpot King');
assert.ok(goonies);
assert.equal(goonies.classification,'INTERNAL_OPERATOR_PAGE_FUNDING_CONFLICT');
assert.equal(goonies.bodyJackpotFunding,0.0232);
assert.equal(goonies.footerJackpotFunding,0.0038);
assert.equal(goonies.safeFundingConfiguration,null);
assert.equal(goonies.safeForExecutionFingerprint,false);
assert.equal(e.sameFamilyControlledComparison.samePublishedBaseRtp,true);
assert.equal(e.sameFamilyControlledComparison.sameVisibleEntryCount,true);
assert.equal(e.sameFamilyControlledComparison.sharedJackpotKingPool,true);
assert.equal(e.sameFamilyControlledComparison.megaBarsFundingDisclosureInternallyConsistent,false);
assert.equal(e.sameFamilyControlledComparison.exactFundingProfileDifferenceProven,false);
assert.equal(e.baseRtpScreen.highestCleanBaseRtp,0.955);
assert.equal(e.baseRtpScreen.cleanLeader,'Mega Bars Fortune Wheel: Jackpot King');
assert.equal(e.baseRtpScreen.excludedSameBaseConflict,'Mega Bars: Jackpot King');
assert.equal(e.baseRtpScreen.notAPlaySignal,true);
const pig=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='The Pig Wizard: Jackpot King');
assert.ok(pig);
assert.equal(pig.safeToAddFundingToBaseAsRtp,false);
const wish=e.ambiguousOrLegacyDisclosures.find(x=>x.game==='Wish Upon a Leprechaun: Jackpot King');
assert.ok(wish);
assert.equal(wish.safeForExecutionFingerprint,false);
const slots=e.ambiguousOrLegacyDisclosures.find(x=>x.game==="Slots O' Gold: Jackpot King");
assert.ok(slots);
assert.equal(slots.safeForSpainSeedInference,false);
assert.equal(e.execution.decision,'NO_PLAY');
for(const key of ['identityVerified','thresholdVerified','stakeVerified','strategyVerified','rulesFingerprintVerified','prospectiveValidationPassed']) assert.equal(e.execution[key],false);
assert.equal(e.hardGuards.fundingIsNotHazard,true);
assert.equal(e.hardGuards.fundingIsNotRtpUnlessExplicitlyProven,true);
assert.equal(e.hardGuards.sameBaseSameTriggerSamePoolDoesNotResolveFundingConflict,true);
assert.equal(e.hardGuards.internalBodyFooterConflictCannotPopulateCleanConfiguration,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

console.log('edge-jpk-spain-disclosure-taxonomy-v1.test.mjs: PASS');
