import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/diamond-spain-cross-operator-v1.json','utf8'));
assert.equal(e.status,'RESEARCH_ONLY_NO_PLAY');
assert.equal(e.realMoneyAllowed,false);
assert.equal(e.brandPages.length,2);
assert.ok(e.brandPages.every(x=>x.publishedRtpPct===95.44));
assert.ok(e.brandPages.every(x=>x.fixedPaylines===5));
assert.ok(e.brandPages.every(x=>x.diamondSpecificContributionPct===null));
assert.notEqual(e.brandPages[0].legalOperator,e.brandPages[1].legalOperator);
assert.ok(e.brandPages.every(x=>x.corporateGroup==="Bally's Group"));
assert.equal(e.corporateRelationshipEvidence.separateSpanishLegalOperators,true);
assert.equal(e.corporateRelationshipEvidence.sameCorporateGroup,true);
assert.equal(e.corporateRelationshipEvidence.independentProviderConfigurationEvidence,false);
assert.equal(e.crossBrandFingerprint.publishedRtpMatches,true);
assert.equal(e.crossBrandFingerprint.fingerprintStrength,'SAME_GROUP_CROSS_BRAND_SPAIN_CORROBORATION');
assert.equal(e.crossBrandFingerprint.independentReplicationClaimAllowed,false);
assert.equal(e.crossBrandFingerprint.independentBackendOrMathConfigurationProven,false);
assert.equal(e.crossBrandFingerprint.sameJackpotPoolProven,false);
assert.equal(e.crossBrandFingerprint.sameContributionPctProven,false);
assert.equal(e.crossBrandFingerprint.sameTriggerProbabilityProven,false);
assert.equal(e.regulatoryRetrievalTarget.article8RequiresJackpotAllocationPercentageDisclosure,true);
assert.equal(e.regulatoryRetrievalTarget.diamondSpecificSpainContributionPct,null);
assert.equal(e.ballyComparator.safeToTransferContributionPctToSpain,false);
assert.equal(e.ballyComparator.safeToComputeSpainBreakEven,false);
assert.equal(e.scientificEffect.independentReplicationObtained,false);
assert.equal(e.scientificEffect.breakEvenAvailable,false);
assert.equal(e.scientificEffect.thresholdEUR,null);
assert.equal(e.scientificEffect.decision,'NO_PLAY');
for(const key of ['identityVerified','thresholdVerified','stakeVerified','strategyVerified','rulesFingerprintVerified','prospectiveValidationPassed'])assert.equal(e.execution[key],false);
assert.equal(e.hardGuards.sameCorporateGroupIsNotIndependentReplication,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

console.log('edge-diamond-spain-cross-operator-v1.test.mjs: PASS');
