import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/galicia-type-c-local-fingerprint-surface-v1.json','utf8'));
const f=e.survivingPrimarySource.facts;

assert.equal(e.status,'CURRENT_PRIMARY_REGULATORY_LOCAL_FINGERPRINT_SURFACE_IDENTIFIED_NO_PLAY');
assert.equal(e.jurisdiction,'ES-GA');
assert.equal(e.realMoneyAllowed,false);
assert.equal(e.currentRegulationStatus.decreto39_2008Status,'EN_VIGOR_WITH_EXPRESS_PARTIAL_REPEALS');
assert.equal(e.currentRegulationStatus.facts.decreto39_2008Article22ExpresslyRepealed,true);
assert.equal(e.currentRegulationStatus.facts.article21StillPresentInConsolidatedText,true);
assert.equal(e.currentRegulationStatus.facts.article23StillPresentInConsolidatedText,true);
assert.equal(e.currentRegulationStatus.facts.article38StillPresentInConsolidatedText,true);
assert.equal(e.currentRegulationStatus.facts.repealedArticle22ExcludedFromCurrentProof,true);
assert.equal(f.typeCPriceFixedPerModelInRegistrationResolution,true);
assert.equal(f.typeCMaxPrizeFixedPerModelInRegistrationResolution,true);
assert.equal(f.typeCMinimumStatisticalReturnPctFloor,80);
assert.equal(f.typeCMayUseMultiplePaylines,true);
assert.equal(f.typeCMayBeMultidenomination,true);
assert.equal(f.typeCFrontOrVideoMustShowGameRules,true);
assert.equal(f.typeCFrontOrVideoMustShowAcceptedDenominationValues,true);
assert.equal(f.typeCFrontOrVideoMustShowWinningCombinationsAndPrizeAmounts,true);
assert.equal(f.typeCFrontOrVideoMustShowMinimumReturnPercentage,true);
assert.equal(f.article21RequiresCommercialModelName,true);
assert.equal(f.article21RequiresCompleteTypeCGameDescription,true);
assert.equal(f.article21ProtectsTechnicalDocumentationFromThirdPartyAccess,true);
assert.equal(f.article23RequiresExteriorPhotos,true);
assert.equal(f.article23RequiresOperatingMemory,true);
assert.equal(f.article23RequiresGameStorageMediumForTypeC,true);
assert.equal(f.article23RequiresCounterDescriptionAndMetrologyEvidenceForTypeC,true);
assert.equal(f.article23OperatingMemoryStatesBetPrice,true);
assert.equal(f.article23OperatingMemoryStatesMaximumPrizeAndGainPlan,true);
assert.equal(f.article23OperatingMemoryStatesTheoreticalPrizePercentage,true);
assert.equal(f.article23OperatingMemoryStatesReturnIncreaseMechanisms,true);
assert.equal(f.article23OperatingMemoryStatesOtherMechanismsOrDevices,true);
assert.equal(f.factoryPlateMustShowManufacturerRegistrationCode,true);
assert.equal(f.factoryPlateMustShowGaliciaModelRegistrationCode,true);
assert.equal(f.factoryPlateMustShowMachineSeriesAndNumber,true);
assert.equal(f.manufacturingCertificateIncludesTypeAndModelName,true);
assert.equal(f.manufacturingCertificateIncludesModelRegistryNumberAndMachineSerial,true);
assert.equal(f.exploitationAuthorizationIndividualizesSpecificMachineAgainstHomologatedModel,true);
assert.equal(f.exploitationAuthorizationTravelsWithMachine,true);
assert.equal(f.substantialModificationIncludesPriceGameProgramOrGainPlan,true);
assert.equal(f.substantialModificationKeepsRegistryNumberWithAlphabeticSuffix,true);
assert.equal(e.currentRegistrationProcedure.procedure,'PR326X');
assert.equal(e.currentRegistrationProcedure.facts.typeCRegistrationProcedureCurrent,true);
assert.equal(e.currentRegistrationProcedure.facts.requiresCommercialModelName,true);
assert.equal(e.currentRegistrationProcedure.facts.requiresCompleteGameDescription,true);
assert.equal(e.currentRegistrationProcedure.facts.requiresOperatingMemory,true);
assert.equal(e.currentRegistrationProcedure.facts.requiresGameStorageMedium,true);
assert.equal(e.currentRegistrationProcedure.facts.requiresCounterTypeDescriptionAndConformityEvidence,true);
assert.equal(e.currentLawSource.facts.registerStoresModelDenomination,true);
assert.equal(e.currentLawSource.facts.registerStoresGeneralCharacteristics,true);
assert.equal(e.currentLawSource.facts.decreto39_2008Article22ExpresslyRepealed,true);
assert.equal(e.fieldCaptureProtocol.requiresWager,false);
assert.ok(e.fieldCaptureProtocol.minimumHighValueImages.length>=3);
assert.equal(e.closureImpact.closesAnyScarabGateNow,false);
assert.equal(e.closureImpact.noWagerLocalIdentifierRecoveryLegallySupported,true);
assert.equal(e.closureImpact.currentRulesConfirmTechnicalFingerprintArtifactsExist,true);
assert.equal(e.closureImpact.fullTechnicalDossierExpectedToBeThirdPartyInaccessible,true);
assert.equal(e.closureImpact.shortestPathChangedFromPublicDossierSearchToExactMachineCapture,true);
assert.equal(e.closureImpact.realMoneyAllowed,false);
assert.equal(e.hardGuards.repealedArticle22NeverUsedAsCurrentAuthority,true);
assert.equal(e.hardGuards.survivingArticle21And23MayBeUsedAsCurrentConsolidatedAuthority,true);
assert.equal(e.hardGuards.legalDisclosureRequirementDoesNotProveExactLocalValuesUntilObserved,true);
assert.equal(e.hardGuards.minimumReturnDisplayDoesNotEqualConfiguredRtpUnlessItsSemanticsAreVerified,true);
assert.equal(e.hardGuards.modelRegistryCodeDoesNotByItselfIdentifySoftwareBuildUnlessMappedByEvidence,true);
assert.equal(e.hardGuards.technicalDocumentationConfidentialityDoesNotBlockExactMachineVisualCapture,true);
assert.equal(e.hardGuards.noWagerNeededForThisCaptureProtocol,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

assert.equal(Object.hasOwn(f,'technicalRegistrationDossierHasConfidentialityProtection'),false,'legacy ambiguous article mapping must not return');

console.log('galicia-type-c-local-fingerprint-surface-v1.test.mjs: PASS');
