import assert from 'node:assert/strict';
import {POWERPLAY_CONTRACTS,rankByBaseLoss,requiredNetCaptureProbability,executionGate,providerTierForTickerCode,STATUS} from '../digital-twins/games/jokerbet-playtech-powerplay.mjs';
assert.equal(POWERPLAY_CONTRACTS.djinn.separatedBasePct,93.50);
assert.equal(POWERPLAY_CONTRACTS.mammoth.separatedBasePct,93.48);
assert.equal(rankByBaseLoss()[0].gameId,'djinn');
assert.equal(providerTierForTickerCode('ptjp-1').tier,'Mega');
assert.equal(providerTierForTickerCode('ptjp-3').tier,'Peak');
assert.equal(providerTierForTickerCode('ptjp-7').tier,'Mini');
assert.equal(providerTierForTickerCode('ptjp-999'),null);
assert.ok(requiredNetCaptureProbability({gameId:'djinn',stakeEUR:1,jackpotAwardEUR:1000}) < requiredNetCaptureProbability({gameId:'jokerRush',stakeEUR:1,jackpotAwardEUR:1000}));
assert.equal(executionGate({}).decision,'NO_PLAY');
const stillNo=executionGate({gameId:'djinn',stakeEUR:1,liveTickerCode:'ptjp-3',liveAmountEUR:1000,displayedBoundaryEUR:1100,netCaptureProbabilityLowerBound:0,runtimeBinding:STATUS.VERIFIED_OPERATOR_BOUND,freshnessMs:100});
assert.equal(stillNo.decision,'NO_PLAY');assert.equal(stillNo.tier,'Peak');
console.log('jokerbet-playtech-powerplay.test.mjs: PASS');
