import assert from 'node:assert/strict';
import {summarizeMermaidCrossBetLeverage,screenMermaidPearlJackpotExercise,screenMermaidBuildExerciseCycle,mermaidStructuralThresholdTable} from '../edge-backend/src/mermaid-frenzy-cross-bet-pearl-option-v1.mjs';
let r=summarizeMermaidCrossBetLeverage({currentPearlMultiplier:10,buildStakeEUR:.20,exerciseStakeEUR:7.50});
assert.equal(r.ok,true);
assert.equal(r.stakeLeverageRatio,37.5);
assert.equal(r.jackpotValues.MINI.exerciseStakeEUR,750);
assert.equal(r.jackpotValues.MEGA.exerciseStakeEUR,37500);
assert.equal(r.practiceVerdict,'WAIT_FOR_RUNTIME_CROSS_BET_STATE_CONFIRMATION');
r=screenMermaidPearlJackpotExercise({currentPearlMultiplier:10,exerciseStakeEUR:7.50,minimumJackpotTier:'MINI'});
assert.equal(r.metrics.breakEvenEventProbabilityPct,1);
assert.equal(r.practiceVerdict,'WAIT_FOR_EXACT_CURRENT_MULTIPLIER_STATE');
r=screenMermaidPearlJackpotExercise({currentPearlMultiplier:10,exerciseStakeEUR:7.50,minimumJackpotTier:'MINI',exactCurrentMultiplierObserved:true,runtimeMultiplierSurvivalAcrossBetChangeVerified:true,probabilityWinningPearlCombinationContainsAtLeastTierNextSpin:.011});
assert.equal(r.practiceVerdict,'CONSERVATIVE_POSITIVE_MERMAID_EXERCISE_CANDIDATE');
assert.equal(r.execution.realMoneyAllowed,false);
r=screenMermaidBuildExerciseCycle({currentPearlMultiplier:10,exerciseStakeEUR:7.50,minimumJackpotTier:'MINI',expectedNetBuildCostEUR:1,buildTransitionKernelVerified:true,probabilityWinningPearlCombinationContainsAtLeastTierNextSpin:.012});
assert.equal(r.practiceVerdict,'CONSERVATIVE_POSITIVE_MERMAID_BUILD_EXERCISE_CYCLE_CANDIDATE');
assert.equal(r.cycleMetrics.cycleNetEvLowerBoundEUR,.5);
r=screenMermaidBuildExerciseCycle({currentPearlMultiplier:10,exerciseStakeEUR:7.50,minimumJackpotTier:'MINI',expectedNetBuildCostEUR:3,buildTransitionKernelVerified:true,probabilityWinningPearlCombinationContainsAtLeastTierNextSpin:.012});
assert.equal(r.practiceVerdict,'NON_POSITIVE_MERMAID_CYCLE_LOWER_BOUND');
const t=mermaidStructuralThresholdTable({buildStakeEUR:.20,exerciseStakeEUR:7.50});
assert.equal(t.rows.length,40);
assert.equal(t.stakeLeverageRatio,37.5);
assert.equal(t.rows.find(x=>x.multiplier===10&&x.tier==='MEGA').breakEvenOneSpinEventProbabilityPct,.02);
console.log('mermaid-frenzy-cross-bet-pearl-option-v1.test.mjs: PASS');
