import assert from 'node:assert/strict';
import fs from 'node:fs';

const e=JSON.parse(fs.readFileSync('loterias-ai/edge-live/evidence/spain-igt-physical-variable-state-v1.json','utf8'));
assert.equal(e.mode,'RESEARCH_ONLY_NO_PLAY');
assert.equal(e.realMoneyAllowed,false);
assert.equal(e.venue.name,'Casino La Toja');
assert.equal(e.venue.currentPhysicalInstallationClaim,true);
assert.deepEqual(e.venue.publishedIgtCrystalTitles,['Ocean’s Magic','Scarab']);

const scarab=e.candidates.find(x=>x.id==='casino-la-toja-scarab-igt');
assert.ok(scarab);
assert.equal(scarab.venueTitleExactMatch,true);
assert.equal(scarab.currentSpainPresence.verifiedFromVenueOfficialPage,true);
assert.equal(scarab.globalMechanismComparator.verifiedFacts.paylines,75);
assert.equal(scarab.globalMechanismComparator.verifiedFacts.cycleSpins,10);
assert.equal(scarab.globalMechanismComparator.verifiedFacts.previousPlayerCanLeaveWildState,true);
assert.equal(scarab.globalMechanismComparator.strategyTransferToSpainAllowed,false);
assert.deepEqual(scarab.crossVariantStructuralEvidence.igtOfficialBrochure.lineOptions,[40,75]);
assert.deepEqual(scarab.crossVariantStructuralEvidence.igtOfficialBrochure.costToCoverAllLinesCredits,{40:40,75:75});
assert.equal(scarab.crossVariantStructuralEvidence.fortyLineRulesScreenshot.screenShowsTotalBetCredits,40);
assert.deepEqual(scarab.crossVariantStructuralEvidence.fortyLineRulesScreenshot.wildPayMultipliers,{2:2,3:20,4:50,5:200});
assert.equal(scarab.crossVariantStructuralEvidence.seventyFiveLineRules.costToCoverCredits,75);
assert.deepEqual(scarab.crossVariantStructuralEvidence.austrianRegulatedRules.wildPayMultipliers,{2:2,3:20,4:50,5:200});
assert.equal(scarab.deterministicLowerBoundDiscovery.discovered,true);
assert.equal(scarab.deterministicLowerBoundDiscovery.proofType,'DISTRIBUTION_FREE_VISIBLE_STATE_LOWER_BOUND');
assert.deepEqual(scarab.deterministicLowerBoundDiscovery.fullPrefixReelsReturnMultiples,{2:2,3:20,4:50,5:200});
assert.equal(scarab.deterministicLowerBoundDiscovery.examplesInBetUnits.twoFullPrefixReelsAfterGame9.minimumNet,1);
assert.equal(scarab.deterministicLowerBoundDiscovery.examplesInBetUnits.threeFullPrefixReelsAfterGame1.minimumNet,11);
assert.equal(scarab.deterministicLowerBoundDiscovery.localExecutionAuthority,false);
assert.equal(scarab.deterministicLowerBoundDiscovery.candidateForExecutionContractOnly,true);
assert.equal(scarab.deterministicLowerBoundDiscovery.realMoneyAllowed,false);
assert.equal(scarab.localFingerprintGates.abandonedBordersVisibleAfterPlayerChangeVerified,false);
assert.equal(scarab.localFingerprintGates.exactPaytableMatchesTwoTwentyFiftyTwoHundred,false);
assert.equal(scarab.localFingerprintGates.oneCreditPerActiveLineBaseScalingVerified,false);
assert.equal(scarab.localFingerprintGates.deterministicBoundApplicableLocally,false);
assert.equal(scarab.decision.maxSpins,0);
assert.equal(scarab.decision.maxTotalStakeEUR,0);
assert.equal(scarab.decision.realMoneyAllowed,false);

const ocean=e.candidates.find(x=>x.id==='casino-la-toja-oceans-magic-igt');
assert.ok(ocean);
assert.equal(ocean.venueTitleExactMatchToCanonical,false);
assert.equal(ocean.globalMechanismComparator.verifiedFacts.variableStateClassification,true);
assert.equal(ocean.globalMechanismComparator.verifiedFacts.bubbleStateCanBeAbandonedByPreviousPlayer,true);
assert.equal(ocean.globalMechanismComparator.verifiedFacts.positivePlayerAdvantageCanExistInFavorableBubblePositions,true);
assert.deepEqual(ocean.globalMechanismComparator.analysisCalibration.simulatedBaseReturnPctRange,[85,86]);
assert.equal(ocean.globalMechanismComparator.strategyTransferToSpainAllowed,false);
assert.equal(ocean.localFingerprintGates.canonicalTitleScreenVerified,false);
assert.equal(ocean.localFingerprintGates.bubblePersistenceVisibleAcrossPlayerChangeVerified,false);
assert.equal(ocean.decision.maxSpins,0);
assert.equal(ocean.decision.realMoneyAllowed,false);

assert.equal(e.portfolioFinding.currentSpainPhysicalVenuePublishesAtLeastOneExactDocumentedVariableStateApTitle,true);
assert.equal(e.portfolioFinding.exactTitle,'Scarab');
assert.equal(e.portfolioFinding.scarabDeterministicLowerBoundDiscovered,true);
assert.equal(e.hardGuards.venueTitleDoesNotProveComparatorConfiguration,true);
assert.equal(e.hardGuards.foreignStrategyDoesNotAutoTransfer,true);
assert.equal(e.hardGuards.crossVariantEvidenceDoesNotProveLocalPaytable,true);
assert.equal(e.hardGuards.deterministicTheoremDoesNotBypassLocalFingerprint,true);
assert.equal(e.hardGuards.noWageringForFingerprintResearch,true);
assert.equal(e.hardGuards.realMoneyAllowed,false);

console.log('spain-igt-physical-variable-state-v1.test.mjs: PASS');
