import assert from 'node:assert/strict';
import {evaluateSportingLegendsOverdueGreenRoute} from '../casino/jackpots/sporting-legends-overdue-green-route-v1.mjs';
const before={code:'sljp-1',requestCasino:'BETFAIR_ES_IMS',instanceCode:'sporting',local:0,currency:'EUR',guaranteedHitTime:1000,gameTimestamp:999,winCount:7,amount:100.02};
const after={...before,gameTimestamp:1001,amount:100.03};
const base={before,after,nowEpochSeconds:1002,exactBetfairSpainTickerImsBindingVerified:true,betfairFirstBetFollowingDayRuleVerified:true,providerGuaranteedHitTimeDefinesFollowingDayBoundaryVerified:true,conservativeBaseRtpPct:93.03,stakeEUR:0.25,currentDailyAmountExactVerified:true,stakeAtDecisionExactVerified:true,measuredActionLatencySeconds:0.4,measuredActionLatencyVerified:true,frozenActionLatencyCeilingSeconds:1,frozenProtocolId:'p1',dryRunCycles:[{protocolId:'p1',observedProspectively:true,protocolFrozenBeforeObservation:true,comparableCycleDefinitionVerified:true,detectedOverdueStateVerified:true,sameBetfairBindingVerified:true,postDetectionSurvivalSeconds:2}]};
let r=evaluateSportingLegendsOverdueGreenRoute(base);
assert.equal(r.decision,'GREEN');
assert.equal(r.realMoneyAllowed,true);
assert.equal(r.maxSpins,1);
assert.ok(Math.abs(r.empiricalRaceBound.firstBetRaceProbabilityLowerBound-0.05)<1e-10);
assert.ok(r.firstBetProbabilityLowerBound>r.breakEvenFirstBetProbability);
r=evaluateSportingLegendsOverdueGreenRoute({...base,dryRunCycles:[{...base.dryRunCycles[0],postDetectionSurvivalSeconds:0.5}]});
assert.equal(r.decision,'NO_PLAY');
assert.equal(r.realMoneyAllowed,false);
r=evaluateSportingLegendsOverdueGreenRoute({...base,measuredActionLatencySeconds:1.1});
assert.equal(r.reason,'MEASURED_LATENCY_EXCEEDS_FROZEN_CEILING');
r=evaluateSportingLegendsOverdueGreenRoute({...base,exactBetfairSpainTickerImsBindingVerified:false});
assert.equal(r.decision,'NO_PLAY');
assert.equal(r.reason,'BETFAIR_SPAIN_TICKER_IMS_NOT_VERIFIED');
console.log('sporting-legends-overdue-green-route-v1.test.mjs: PASS');
