import assert from 'node:assert/strict';
import {evaluateState9ParkingOption,sweepState9ParkingSensitivity} from '../edge-backend/src/streak-of-luck-state9-parking-option-v1.mjs';
let r=evaluateState9ParkingOption({observedStreakState:9,totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0,probabilityJackpotBeforeState9TerminalLoss:.2,externalJackpotResetHazardPerPeriod:.05,jackpotGrowthEURPerPeriod:5,waitPeriods:1});
assert.equal(r.ok,true);
assert.equal(r.practiceVerdict,'BLOCKED_BONUS_DICE_SEQUENCE_UNRESOLVED');
assert.equal(r.execution.realMoneyAllowed,false);
r=evaluateState9ParkingOption({observedStreakState:9,bonusDiceSequencingResolved:true,totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0,probabilityJackpotBeforeState9TerminalLoss:.2,externalJackpotResetHazardPerPeriod:.05,jackpotGrowthEURPerPeriod:5,waitPeriods:1});
assert.equal(r.ok,true);
assert.equal(r.metrics.exerciseNowNetEvEUR,34);
assert.equal(r.metrics.survivalProbability,.95);
assert.ok(r.metrics.waitOptionExpectedValueEUR>0);
r=evaluateState9ParkingOption({observedStreakState:8,bonusDiceSequencingResolved:true,totalStakeEUR:1,jackpotAwardFloorEUR:175,probabilityJackpotBeforeState9TerminalLoss:.2,externalJackpotResetHazardPerPeriod:.05,jackpotGrowthEURPerPeriod:5,waitPeriods:1});
assert.equal(r.ok,false);
let s=sweepState9ParkingSensitivity({totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0,waitPeriods:1});
assert.equal(s.practiceVerdict,'BLOCKED_BONUS_DICE_SEQUENCE_UNRESOLVED');
assert.equal(s.rows.length,0);
s=sweepState9ParkingSensitivity({bonusDiceSequencingResolved:true,totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0,waitPeriods:1});
assert.equal(s.rows.length,150);
assert.equal(s.execution.decision,'NO_PLAY');
console.log('streak-of-luck-state9-parking-option-v1.test.mjs: PASS');
