import assert from 'node:assert/strict';
import {screenStreak9NextSpin} from '../edge-backend/src/streak-of-luck-state9-one-spin-screen-v1.mjs';
let r=screenStreak9NextSpin({observedStreakState:9,totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0});
assert.equal(r.ok,true);
assert.equal(r.metrics.breakEvenJackpotBeforeTerminalLossProbabilityPct,0.57142857);
assert.equal(r.practiceVerdict,'BLOCKED_BONUS_DICE_SEQUENCE_UNRESOLVED');
assert.equal(r.execution.realMoneyAllowed,false);
r=screenStreak9NextSpin({observedStreakState:9,totalStakeEUR:1,jackpotAwardFloorEUR:175,sixtyFreeSpinsValueFloorEUR:0,probabilityJackpotBeforeState9TerminalLoss:.01,bonusDiceSequencingResolved:true});
assert.equal(r.practiceVerdict,'CONSERVATIVE_POSITIVE_STATE9_ONE_SPIN_CANDIDATE');
r=screenStreak9NextSpin({observedStreakState:8,totalStakeEUR:1,jackpotAwardFloorEUR:175});
assert.equal(r.reason,'EXACT_OBSERVED_STREAK_STATE_9_REQUIRED');
console.log('streak-of-luck-state9-one-spin-screen-v1.test.mjs: PASS');
