/* Loterías AI — SELAE Adapter */
(function(root){'use strict';
function text(v){return v==null?'':String(v).trim()}function toDateISO(s){const v=text(s);let m=v.match(/(\d{2})\/(\d{2})\/(\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=v.match(/(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:null}function nums(s){return (text(s).match(/\b\d{1,2}\b/g)||[]).map(Number)}function unique(a){return [...new Set((a||[]).map(Number).filter(Number.isFinite))]}
const SPECS={bonoloto:{pick:6,max:49},primitiva:{pick:6,max:49},euromillones:{pick:5,max:50,secondaryPick:2,secondaryMax:12},'gordo-primitiva':{pick:5,max:54},eurodreams:{pick:6,max:40},'loteria-nacional':{pick:1,max:99999},navidad:{pick:1,max:99999},nino:{pick:1,max:99999}};
function extractCombination(s,count){const patterns=[/combinaci[oó]n ganadora[^\d]*(\d{1,2}(?:\s*[-–·,]\s*\d{1,2}){2,8})/i,/resultado[^\d]*(\d{1,2}(?:\s*[-–·,]\s*\d{1,2}){2,8})/i];for(const p of patterns){const m=text(s).match(p);if(m){const a=unique(nums(m[1]));if(a.length>=count)return a.slice(0,count)}}return []}
function extractNumeric(gameId,raw){const s=text(raw),spec=SPECS[gameId];if(!spec)throw new Error('unsupported_game');const draw={gameId,drawDate:toDateISO(s),main:extractCombination(s,spec.pick)};let m;if(gameId==='euromillones'){m=s.match(/estrellas?[^\d]*(\d{1,2})\D+(\d{1,2})/i);draw.secondary=m?[Number(m[1]),Number(m[2])]:[]}if(['bonoloto','primitiva'].includes(gameId)){m=s.match(/Complementario\s*:?\s*(?:C\()?\s*(\d{1,2})/i);draw.complementary=m?Number(m[1]):null;m=s.match(/Reintegro\s*:?\s*(?:R\()?\s*(\d)/i);draw.reintegro=m?Number(m[1]):null}if(gameId==='gordo-primitiva'){m=s.match(/Clave\s*:?\s*(\d)/i);draw.extra=m?Number(m[1]):null}if(gameId==='eurodreams'){m=s.match(/Sue(?:ñ|n)o\s*:?\s*(\d)/i);draw.extra=m?Number(m[1]):null}return draw}
function parseListingDates(raw){const found=[],re=/(\d{2}\/\d{2}\/\d{4})/g;let m;while((m=re.exec(text(raw))))found.push(toDateISO(m[1]));return [...new Set(found)].filter(Boolean).sort()}
function validateNumericDraw(draw){const spec=SPECS[draw&&draw.gameId],issues=[];if(!spec)return{ok:false,issues:['unsupported_game']};if(!/^\d{4}-\d{2}-\d{2}$/.test(text(draw.drawDate)))issues.push('invalid_date');const main=Array.isArray(draw.main)?draw.main:[];if(main.length!==spec.pick)issues.push('invalid_pick_count');if(new Set(main).size!==main.length)issues.push('duplicate_main_number');if(main.some(n=>!Number.isInteger(n)||n<1||n>spec.max))issues.push('main_out_of_range');if(spec.secondaryPick){const sec=Array.isArray(draw.secondary)?draw.secondary:[];if(sec.length!==spec.secondaryPick)issues.push('invalid_secondary_count');if(sec.some(n=>!Number.isInteger(n)||n<1||n>spec.secondaryMax))issues.push('secondary_out_of_range')}return{ok:issues.length===0,issues}}
function buildCanonical(draw,source){const v=validateNumericDraw(draw);return{drawId:`${draw.gameId}-${draw.drawDate}`,gameId:draw.gameId,drawDate:draw.drawDate,result:{main:draw.main,secondary:draw.secondary||[],complementary:draw.complementary??null,reintegro:draw.reintegro??null,extra:draw.extra??null},source:{official:true,provider:'SELAE',url:source&&source.url||null,format:source&&source.format||'html'},verification:{status:v.ok?'VALIDATED_BY_PARSER':'REJECTED',validatedAt:new Date().toISOString(),issues:v.issues}}}
root.SELAEAdapter={SPECS,toDateISO,parseListingDates,extractNumeric,validateNumericDraw,buildCanonical};})(typeof window!=='undefined'?window:globalThis);