export const STATUS=Object.freeze({VERIFIED_OPERATOR_BOUND:'VERIFIED_OPERATOR_BOUND',VERIFIED_REGULATOR_BOUND:'VERIFIED_REGULATOR_BOUND',VERIFIED_PROVIDER_BOUND:'VERIFIED_PROVIDER_BOUND',CROSS_OPERATOR_ONLY:'CROSS_OPERATOR_ONLY',EMPIRICAL_REALIZED_ONLY:'EMPIRICAL_REALIZED_ONLY',ESTIMATED:'ESTIMATED',UNKNOWN:'UNKNOWN'});
export const RULES=Object.freeze({operator:'SELAE',game:'Quíntuple Plus',pricePerSimpleBetEUR:1,prizePoolSharePct:55,firstCategoryRequirement:'5 winners + second place in race 5',specialRequirement:'exactly one first-category winning receipt',status:STATUS.VERIFIED_OPERATOR_BOUND});
export const CONTRACT=Object.freeze({operator:{value:'SELAE / loteriasyapuestas.es',status:STATUS.VERIFIED_OPERATOR_BOUND},game:{value:'Quíntuple Plus',status:STATUS.VERIFIED_OPERATOR_BOUND},pricePerBetEUR:{value:1,status:STATUS.VERIFIED_OPERATOR_BOUND},totalPrizeFundPct:{value:55,status:STATUS.VERIFIED_OPERATOR_BOUND},firstCategoryPct:{value:24,status:STATUS.VERIFIED_OPERATOR_BOUND},secondCategoryPct:{value:7,status:STATUS.VERIFIED_OPERATOR_BOUND},thirdCategoryPct:{value:7,status:STATUS.VERIFIED_OPERATOR_BOUND},fourthCategoryPct:{value:7,status:STATUS.VERIFIED_OPERATOR_BOUND},nextSpecialCategoryPct:{value:10,status:STATUS.VERIFIED_OPERATOR_BOUND},minimumPaidCategoryPrizeEUR:{value:1.50,status:STATUS.VERIFIED_OPERATOR_BOUND},specialRequiresSingleFirstCategoryReceipt:{value:true,status:STATUS.VERIFIED_OPERATOR_BOUND},taxExemptPerBetPrizeEUR:{value:40000,status:STATUS.VERIFIED_REGULATOR_BOUND},taxRateOnExcess:{value:0.20,status:STATUS.VERIFIED_REGULATOR_BOUND},publicTicketDistribution:{value:null,status:STATUS.UNKNOWN},trueOutcomeProbabilities:{value:null,status:STATUS.UNKNOWN},futureFinalBetCount:{value:null,status:STATUS.UNKNOWN},specialReceiptGroupingModel:{value:null,status:STATUS.UNKNOWN}});
const FIRST_RATE=0.24;
function prob(x,n){if(!(x>=0&&x<=1))throw new Error(`${n}_0_1_REQUIRED`);return x;}
function positive(x,n){if(!(x>0))throw new Error(`POSITIVE_${n}_REQUIRED`);return x;}
export function netPrizeAfterTaxEUR(grossPrizeEUR,{exemptEUR=40000,taxRate=0.20}={}){if(!(grossPrizeEUR>=0))throw new Error('NONNEGATIVE_PRIZE_REQUIRED');return grossPrizeEUR<=exemptEUR?grossPrizeEUR:grossPrizeEUR-(grossPrizeEUR-exemptEUR)*taxRate;}
export function uniformFirstCategoryCombinationCount(fieldSizes){if(!Array.isArray(fieldSizes)||fieldSizes.length!==5||fieldSizes.some(n=>!Number.isInteger(n)||n<2))throw new Error('FIVE_FIELD_SIZES_AT_LEAST_TWO_REQUIRED');return fieldSizes.reduce((a,b)=>a*b,1)*(fieldSizes[4]-1);}
export function observedWinningTicketCrowdConcentration({totalBets,firstCategoryWinners,fieldSizes}){if(!Number.isInteger(totalBets)||totalBets<=0||!Number.isInteger(firstCategoryWinners)||firstCategoryWinners<0)throw new Error('VALID_COUNTS_REQUIRED');const combinations=uniformFirstCategoryCombinationCount(fieldSizes),observedPublicProbability=firstCategoryWinners/totalBets,uniformProbability=1/combinations;return{totalBets,firstCategoryWinners,combinations,observedPublicProbability,uniformProbability,concentrationVsUniform:firstCategoryWinners===0?0:observedPublicProbability/uniformProbability,scope:'REALIZED_WINNING_COMBINATION_ONLY'};}
export function substituteWithdrawnDorsal({selectedDorsal,withdrawnDorsals,highestDorsal}){if(!Number.isInteger(selectedDorsal)||!Number.isInteger(highestDorsal)||selectedDorsal<1||selectedDorsal>highestDorsal)throw new Error('VALID_DORSAL_REQUIRED');const withdrawn=new Set(withdrawnDorsals||[]);if(!withdrawn.has(selectedDorsal))return selectedDorsal;let d=selectedDorsal;for(let i=0;i<highestDorsal;i++){d=d===1?highestDorsal:d-1;if(!withdrawn.has(d))return d;}throw new Error('NO_PARTICIPATING_DORSAL_AVAILABLE');}
export function expectedShareFactor({otherTickets,publicCombinationProbability}){if(!Number.isInteger(otherTickets)||otherTickets<0)throw new Error('NONNEGATIVE_INTEGER_OTHER_TICKETS_REQUIRED');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');if(otherTickets===0||q===0)return 1;const n=otherTickets+1;return(1-Math.pow(1-q,n))/(n*q);}
export function uniqueGivenHitProbability({otherTickets,publicCombinationProbability}){if(!Number.isInteger(otherTickets)||otherTickets<0)throw new Error('NONNEGATIVE_INTEGER_OTHER_TICKETS_REQUIRED');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');return Math.pow(1-q,otherTickets);}
export function expectedTicketReturnEUR({ticketCostEUR=1,ownOutcomeProbability,otherTickets,publicCombinationProbability,firstCategoryPoolEUR,specialPoolEUR=0,otherReceipts=null,publicFirstCategoryReceiptProbability=null}){positive(ticketCostEUR,'TICKET_COST');const p=prob(ownOutcomeProbability,'OWN_OUTCOME_PROBABILITY');positive(firstCategoryPoolEUR,'FIRST_CATEGORY_POOL');if(!(specialPoolEUR>=0))throw new Error('NONNEGATIVE_SPECIAL_POOL_REQUIRED');const share=expectedShareFactor({otherTickets,publicCombinationProbability});const expectedFirst=p*firstCategoryPoolEUR*share;let uniqueReceipt=null,expectedSpecial=0,specialValued=false;if(specialPoolEUR>0&&otherReceipts!==null&&publicFirstCategoryReceiptProbability!==null){if(!Number.isInteger(otherReceipts)||otherReceipts<0)throw new Error('NONNEGATIVE_INTEGER_OTHER_RECEIPTS_REQUIRED');uniqueReceipt=uniqueGivenHitProbability({otherTickets:otherReceipts,publicCombinationProbability:publicFirstCategoryReceiptProbability});expectedSpecial=p*specialPoolEUR*uniqueReceipt;specialValued=true;}const expectedReturnEUR=expectedFirst+expectedSpecial;return{ticketCostEUR,ownOutcomeProbability:p,otherTickets,publicCombinationProbability,expectedShareFactor:share,uniqueGivenHitProbability:uniqueReceipt,expectedFirstCategoryEUR:expectedFirst,expectedSpecialEUR:expectedSpecial,specialValued,specialExcludedReason:specialValued?null:'RECEIPT_GROUPING_MODEL_NOT_BOUND',expectedReturnEUR,returnRatio:expectedReturnEUR/ticketCostEUR,edgeEUR:expectedReturnEUR-ticketCostEUR};}
export function contrarianScore({ownOutcomeProbability,publicCombinationProbability}){const p=prob(ownOutcomeProbability,'OWN_OUTCOME_PROBABILITY');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');return q===0?(p>0?Infinity:0):p/q;}
export function sensitivitySurface({ownOutcomeProbabilities,publicCombinationProbabilities,otherTicketCounts,firstCategoryPoolsEUR,specialPoolsEUR=[0],ticketCostEUR=1}){const rows=[];for(const p of ownOutcomeProbabilities)for(const q of publicCombinationProbabilities)for(const otherTickets of otherTicketCounts)for(const firstCategoryPoolEUR of firstCategoryPoolsEUR)for(const specialPoolEUR of specialPoolsEUR){const r=expectedTicketReturnEUR({ticketCostEUR,ownOutcomeProbability:p,otherTickets,publicCombinationProbability:q,firstCategoryPoolEUR,specialPoolEUR});rows.push({...r,contrarianScore:contrarianScore({ownOutcomeProbability:p,publicCombinationProbability:q}),positiveEV:r.returnRatio>1});}return rows;}
export function firstCategoryBaseGrossReturnRatio({trueTicketProbability,publicTicketProbability,totalBets,firstCarryoverEUR=0}){if(!(trueTicketProbability>=0&&trueTicketProbability<=1)||!(firstCarryoverEUR>=0))throw new Error('VALID_PROBABILITY_AND_CARRYOVER_REQUIRED');const pool=FIRST_RATE*totalBets+firstCarryoverEUR,share=expectedShareFactor({otherTickets:Math.max(0,totalBets-1),publicCombinationProbability:publicTicketProbability});return trueTicketProbability*pool*share;}
export function firstCategoryTaxConservativeReturnRatio(input){const gross=firstCategoryBaseGrossReturnRatio(input),pool=FIRST_RATE*input.totalBets+(input.firstCarryoverEUR||0);if(pool<=CONTRACT.taxExemptPerBetPrizeEUR.value)return gross;return gross*(1-CONTRACT.taxRateOnExcess.value);}
export function finiteCrowdBreakEvenTrueToPublicRatio({totalBets,publicTicketProbability,firstCarryoverEUR=0}){if(!(publicTicketProbability>0&&publicTicketProbability<=1))return null;const dilutionCapture=1-Math.pow(1-publicTicketProbability,totalBets);const poolFactor=FIRST_RATE+firstCarryoverEUR/totalBets;return 1/(poolFactor*dilutionCapture);}
export function asymptoticFirstCategoryBreakEvenTrueToPublicRatio(){return 1/FIRST_RATE;}
export function classifyTicket({ticket,outcome}){if(!Array.isArray(ticket)||ticket.length!==6||!Array.isArray(outcome)||outcome.length!==6)throw new Error('SIX_SELECTIONS_REQUIRED');let winners=0;for(let i=0;i<5;i++)if(ticket[i]===outcome[i])winners++;const second=ticket[5]===outcome[5];if(winners===5&&second)return 1;if(winners===5)return 2;if(winners===4&&second)return 3;if(winners===4)return 4;return 0;}
export function exactOutcomeProbability({ticket,winProbabilities,race5OrderedProbability}){if(!Array.isArray(ticket)||ticket.length!==6||!Array.isArray(winProbabilities)||winProbabilities.length!==4)throw new Error('FOUR_RACE_WIN_PROBABILITIES_AND_TICKET_REQUIRED');let p=1;for(let i=0;i<4;i++){const x=winProbabilities[i]?.[ticket[i]];if(!(x>=0&&x<=1))throw new Error('BOUND_WIN_PROBABILITY_REQUIRED');p*=x;}const pair=race5OrderedProbability?.[ticket[4]]?.[ticket[5]];if(!(pair>=0&&pair<=1))throw new Error('BOUND_RACE5_ORDERED_PROBABILITY_REQUIRED');return p*pair;}
export function robustFirstCategoryGate(state={}){const required=['trueTicketProbabilityLower','publicTicketProbabilityUpper','finalBetCountLower','ticketBound','raceBound','withdrawalsBound','taxTreatmentBound'];const missing=required.filter(k=>state?.[k]?.status!==STATUS.VERIFIED_OPERATOR_BOUND&&state?.[k]?.status!==STATUS.VERIFIED_REGULATOR_BOUND);if(missing.length)return{decision:'NO_PLAY',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,reason:'BOUND_INPUTS_MISSING',missing};const totalBets=state.finalBetCountLower.value,pTrue=state.trueTicketProbabilityLower.value,pPublic=state.publicTicketProbabilityUpper.value;const gross=firstCategoryBaseGrossReturnRatio({trueTicketProbability:pTrue,publicTicketProbability:pPublic,totalBets,firstCarryoverEUR:0});const netLower=firstCategoryTaxConservativeReturnRatio({trueTicketProbability:pTrue,publicTicketProbability:pPublic,totalBets,firstCarryoverEUR:0});if(!(netLower>1))return{decision:'NO_PLAY',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,reason:'FIRST_CATEGORY_CONSERVATIVE_NET_EV_NOT_POSITIVE',grossLowerReturnRatio:gross,netLowerReturnRatio:netLower};return{decision:'MATH_CANDIDATE_REQUIRES_FRESH_PRE_CLOSE_CONFIRMATION',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,grossLowerReturnRatio:gross,netLowerReturnRatio:netLower,reason:'FIRST_CATEGORY_BASE_POOL_ONLY; CARRYOVER, LOWER_CATEGORIES AND SPECIAL EXCLUDED'};}
export function executionGate(state={}){return robustFirstCategoryGate(state);}
