export const STATUS=Object.freeze({VERIFIED_OPERATOR_BOUND:'VERIFIED_OPERATOR_BOUND',VERIFIED_PROVIDER_BOUND:'VERIFIED_PROVIDER_BOUND',CROSS_OPERATOR_ONLY:'CROSS_OPERATOR_ONLY',ESTIMATED:'ESTIMATED',UNKNOWN:'UNKNOWN'});
export const RULES=Object.freeze({operator:'SELAE',game:'Quíntuple Plus',pricePerSimpleBetEUR:1,prizePoolSharePct:55,firstCategoryRequirement:'5 winners + second place in race 5',specialRequirement:'exactly one first-category winning receipt',status:STATUS.VERIFIED_OPERATOR_BOUND});
function prob(x,n){if(!(x>=0&&x<=1))throw new Error(`${n}_0_1_REQUIRED`);return x;}
function positive(x,n){if(!(x>0))throw new Error(`POSITIVE_${n}_REQUIRED`);return x;}
export function expectedShareFactor({otherTickets,publicCombinationProbability}){if(!Number.isInteger(otherTickets)||otherTickets<0)throw new Error('NONNEGATIVE_INTEGER_OTHER_TICKETS_REQUIRED');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');if(otherTickets===0||q===0)return 1;const n=otherTickets+1;return (1-Math.pow(1-q,n))/(n*q);}
export function uniqueGivenHitProbability({otherTickets,publicCombinationProbability}){if(!Number.isInteger(otherTickets)||otherTickets<0)throw new Error('NONNEGATIVE_INTEGER_OTHER_TICKETS_REQUIRED');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');return Math.pow(1-q,otherTickets);}
export function expectedTicketReturnEUR({ticketCostEUR=1,ownOutcomeProbability,otherTickets,publicCombinationProbability,firstCategoryPoolEUR,specialPoolEUR=0}){positive(ticketCostEUR,'TICKET_COST');const p=prob(ownOutcomeProbability,'OWN_OUTCOME_PROBABILITY');positive(firstCategoryPoolEUR,'FIRST_CATEGORY_POOL');if(!(specialPoolEUR>=0))throw new Error('NONNEGATIVE_SPECIAL_POOL_REQUIRED');const share=expectedShareFactor({otherTickets,publicCombinationProbability});const unique=uniqueGivenHitProbability({otherTickets,publicCombinationProbability});const expectedFirst=p*firstCategoryPoolEUR*share;const expectedSpecial=p*specialPoolEUR*unique;const expectedReturnEUR=expectedFirst+expectedSpecial;return{ticketCostEUR,ownOutcomeProbability:p,otherTickets,publicCombinationProbability,expectedShareFactor:share,uniqueGivenHitProbability:unique,expectedFirstCategoryEUR:expectedFirst,expectedSpecialEUR:expectedSpecial,expectedReturnEUR,returnRatio:expectedReturnEUR/ticketCostEUR,edgeEUR:expectedReturnEUR-ticketCostEUR};}
export function contrarianScore({ownOutcomeProbability,publicCombinationProbability}){const p=prob(ownOutcomeProbability,'OWN_OUTCOME_PROBABILITY');const q=prob(publicCombinationProbability,'PUBLIC_COMBINATION_PROBABILITY');return q===0?(p>0?Infinity:0):p/q;}
export function sensitivitySurface({ownOutcomeProbabilities,publicCombinationProbabilities,otherTicketCounts,firstCategoryPoolsEUR,specialPoolsEUR=[0],ticketCostEUR=1}){const rows=[];for(const p of ownOutcomeProbabilities)for(const q of publicCombinationProbabilities)for(const otherTickets of otherTicketCounts)for(const firstCategoryPoolEUR of firstCategoryPoolsEUR)for(const specialPoolEUR of specialPoolsEUR){const r=expectedTicketReturnEUR({ticketCostEUR,ownOutcomeProbability:p,otherTickets,publicCombinationProbability:q,firstCategoryPoolEUR,specialPoolEUR});rows.push({...r,contrarianScore:contrarianScore({ownOutcomeProbability:p,publicCombinationProbability:q}),positiveEV:r.returnRatio>1});}return rows;}
export function executionGate(state={}){const required=['journeyId','ticketCostEUR','ownOutcomeProbabilityLower','publicCombinationProbabilityUpper','acceptedTickets','firstCategoryPoolEUR','specialPoolEUR','runnerAndWithdrawalsBound','freshnessBound'];const missing=required.filter(k=>state?.[k]?.status!==STATUS.VERIFIED_OPERATOR_BOUND||state?.[k]?.value==null);if(missing.length)return{decision:'NO_PLAY',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,reason:'OPERATOR_BOUND_QUINTUPLE_INPUTS_MISSING',missing};const r=expectedTicketReturnEUR({ticketCostEUR:state.ticketCostEUR.value,ownOutcomeProbability:state.ownOutcomeProbabilityLower.value,otherTickets:Math.max(0,state.acceptedTickets.value-1),publicCombinationProbability:state.publicCombinationProbabilityUpper.value,firstCategoryPoolEUR:state.firstCategoryPoolEUR.value,specialPoolEUR:state.specialPoolEUR.value});return r.returnRatio>1?{decision:'MATH_CANDIDATE_REQUIRES_PRE_CLOSE_FRESHNESS_CONFIRMATION',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,lowerReturnRatio:r.returnRatio,reason:'LOWER_PROBABILITY_AND_UPPER_PUBLIC_DUPLICATION_STILL_POSITIVE'}:{decision:'NO_PLAY',realMoneyAllowed:false,realStakeEUR:0,maxTickets:0,lowerReturnRatio:r.returnRatio,reason:'CONSERVATIVE_RETURN_NOT_ABOVE_ONE'};}
