const DEFAULT_GAME_URL='https://www.botemania.es/';
const DEFAULT_GAME_NAME='Sin oportunidad validada';
const BOT_GRAPHQL='https://www.botemania.es/es/graphql';
const BOT_QUERY='query loadJackpots { jackpots { id amount } redTigerJackpots { id amount } blueprintJackpots { id amount } }';
const SOURCES={
  plan:'./evidence/edge-live-execution-plan-v1.json',
  network:'./evidence/botemania-all-network-live-state-v1.json',
  params:'./evidence/botemania-fishin-execution-parameters-v1.json',
  assets:'./evidence/botemania-fishin-public-assets-probe-v1.json',
  metadata:'../casino/jackpots/evidence/botemania-fishin-metadata-probe-v1.json',
  live:'../casino/jackpots/evidence/botemania-jpk-live-gate-v1.json',
  validation:'../casino/jackpots/evidence/botemania-jpk-allocation-validation-result-v1.json'
};
const $=id=>document.getElementById(id);
const eur=x=>Number.isFinite(Number(x))?Number(x).toLocaleString('es-ES',{style:'currency',currency:'EUR',minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const rtpFmt=x=>{const n=Number(x);if(!Number.isFinite(n))return '—';return `${(Math.abs(n)<=2?n*100:n).toFixed(3)}%`;};
const secAge=t=>{const n=Date.parse(t||'');return Number.isFinite(n)?Math.max(0,Math.floor((Date.now()-n)/1000)):null;};
const time=t=>{const d=new Date(t);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d):'—';};
const clock=()=>new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date());
const escapeHtml=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blockerLabel={STRUCTURAL_VALIDATION_NOT_PASSED:'La estructura prospectiva todavía no está validada.',ECONOMIC_GATE_NOT_PASSED:'El estado económico actual no demuestra expectativa positiva.',EXACT_STAKE_PER_SPIN_NOT_VERIFIED:'Todavía no está verificada la apuesta total exacta por decisión.',SOURCE_NOT_FRESH:'El dato científico no está suficientemente fresco.',SIGNAL_EXPIRED:'La ventana de ejecución ya ha caducado.',LIVE_COUNTER_NOT_FOUND:'No aparece el contador vivo exacto del carril.',LIVE_COUNTER_IDENTITY_NOT_VERIFIED:'La identidad del contador todavía no está verificada.',BREAK_EVEN_THRESHOLD_EUR_NOT_VERIFIED:'Falta convertir el umbral matemático exacto a euros.',CURRENT_STATE_BELOW_BREAK_EVEN:'El estado actual todavía está por debajo del punto de equilibrio.',EXACT_STAKE_NOT_VERIFIED:'Falta verificar el stake exacto de ejecución.',EXECUTION_STRATEGY_NOT_VERIFIED:'Falta validar la estrategia exacta de ejecución.'};
const typeLabel={MUST_BE_WON_BY_PROGRESSIVE_NETWORK:'MUST-BE-WON-BY · PROGRESIVO',PROGRESSIVE_VIDEO_POKER:'VIDEOPÓKER PROGRESIVO',SELECTED_EXECUTION_PLAN:'OPORTUNIDAD ESTRUCTURAL'};
const typeEmoji={PROGRESSIVE_VIDEO_POKER:'🃏',MUST_BE_WON_BY_PROGRESSIVE_NETWORK:'🎰'};
let state={plan:null,network:null,params:null,assets:null,metadata:null,live:null,validation:null,directByKey:{},directPots:null,directAt:null,directOk:false};
async function json(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json();}
async function maybeJson(url){try{return await json(url);}catch{return null;}}
function selectedLane(){const lanes=Array.isArray(state.plan?.lanes)?state.plan.lanes:[];return lanes.find(x=>x?.id===state.plan?.selectedLaneId)||lanes.find(x=>x?.game?.id===state.plan?.game?.id)||null;}
function currentGame(){const lane=selectedLane();return{ id:state.plan?.game?.id||lane?.game?.id||'none',name:state.plan?.game?.name||lane?.game?.name||DEFAULT_GAME_NAME,url:state.plan?.game?.url||lane?.game?.url||DEFAULT_GAME_URL,type:lane?.type||'SELECTED_EXECUTION_PLAN'};}
function directFresh(){const a=secAge(state.directAt);return state.directOk&&a!=null&&a<=10;}
function directRowForLane(lane){const key=lane?.monitor?.key;return directFresh()&&key?state.directByKey?.[key]||null:null;}
function visiblePots(){const direct=state.directPots;if(directFresh()&&direct&&Object.keys(direct).length===3)return direct;return state.live?.current?.potsEUR||{};}
function planReady(){const p=state.plan;if(!p||p.state!=='READY_TO_EXECUTE_MANUALLY'||p?.order?.action!=='PLAY')return false;const until=Date.parse(p?.order?.validUntil||'');return Number.isFinite(until)&&Date.now()<=until&&Number(p?.order?.stakePerSpinEUR)>0&&Number(p?.order?.maxSpins)>0;}
function planPrepare(){const p=state.plan;return p?.state==='PREPARE_OPEN_GAME_NO_BET'&&p?.order?.action==='OPEN_GAME_ONLY_NO_BET';}
function phase(){return planReady()?'GREEN':planPrepare()?'YELLOW':'RED';}
function whyText(){const blockers=Array.isArray(state.plan?.blockers)?state.plan.blockers:[];const ph=phase(),g=currentGame();if(ph==='GREEN')return `Todos los gates de ejecución están vigentes para ${escapeHtml(g.name)}. Confirma que sigue VERDE antes de la primera apuesta y ejecuta exactamente el importe y máximo indicados.`;if(ph==='YELLOW')return `PREPÁRATE: abre Botemania y entra en ${escapeHtml(g.name)}, pero NO apuestes todavía. Espera la orden VERDE.`;if(!blockers.length)return 'No hay una orden ejecutable vigente. EDGE LIVE se mantiene cerrado por seguridad.';return blockers.map(b=>`• ${blockerLabel[b]||escapeHtml(b)}`).join('<br>');}
function renderArtwork(){const g=currentGame();const art=$('gameArt'),bg=$('gameBg');art.style.backgroundImage='';bg.style.backgroundImage='';art.textContent=typeEmoji[g.type]||'🎯';if(g.id!=='fishin-frenzy-jackpot-king')return;const probed=state.assets?.decision?.officialPublicArtworkRecovered===true?state.assets?.decision?.preferredArtworkUrl:null;const graphql=state.metadata?.decision?.officialImageVariantRecovered===true?state.metadata?.decision?.preferredOfficialImageVariant:null;const url=graphql||probed;if(!url)return;art.textContent='';art.style.backgroundImage=`url("${url}")`;bg.style.backgroundImage=`url("${url}")`;}
function renderHeader(){const lane=selectedLane(),g=currentGame(),title=$('gameTitle');$('providerLabel').textContent='BOTEMANIA · EDGE';if(title?.firstChild)title.firstChild.nodeValue=`${g.name} `;$('gameType').textContent=typeLabel[g.type]||String(g.type||'OPORTUNIDAD ESTRUCTURAL').replaceAll('_',' ');$('gameSubtitle').textContent=lane?.monitor?.key?`Contador ${lane.monitor.key} · identidad y umbral gobernados por EDGE`:'Carril estructural seleccionado automáticamente por el motor multi-lane';$('gameCard').href=g.url;$('inspectGame').href=g.url;renderArtwork();}
function renderMetrics(){const lane=selectedLane(),direct=directRowForLane(lane);if(lane?.monitor?.key){const current=Number(direct?.amountEUR??lane?.current?.jackpotEUR),threshold=Number(lane?.economic?.breakEvenJackpotEUR),distance=Number.isFinite(current)&&Number.isFinite(threshold)?threshold-current:null;$('potLabel1').textContent='BOTE ACTUAL';$('potLabel2').textContent='UMBRAL +EV';$('potLabel3').textContent=Number.isFinite(distance)&&distance<=0?'SOBRE UMBRAL':'FALTA PARA +EV';$('potKing').textContent=eur(current);$('potRegal').textContent=eur(threshold);$('potRoyal').textContent=Number.isFinite(distance)?eur(Math.abs(distance)):'—';return;}const pots=visiblePots();$('potLabel1').textContent='JACKPOT KING';$('potLabel2').textContent='REGAL';$('potLabel3').textContent='ROYAL';$('potKing').textContent=eur(pots.JACKPOT_KING);$('potRegal').textContent=eur(pots.REGAL);$('potRoyal').textContent=eur(pots.ROYAL);}
function render(){
  const p=state.plan||{},l=state.live||{},lane=selectedLane(),ph=phase(),ready=ph==='GREEN',prepare=ph==='YELLOW',g=currentGame();renderHeader();renderMetrics();
  $('orderCard').className='order'+(ready?' ready':prepare?' prepare':'');$('decision').textContent=ready?'JUGAR AHORA':prepare?'PREPÁRATE':'NO JUGAR';$('signalState').textContent=ready?'SEÑAL VÁLIDA':prepare?'ABRE EL JUEGO · NO APUESTES':'BLOQUEADO';$('stakePerSpin').textContent=ready?eur(p.order.stakePerSpinEUR):prepare?'ESPERA VERDE':'—';$('maxSpins').textContent=ready?String(p.order.maxSpins):'0';$('maxTotal').textContent=ready?eur(p.order.maxTotalStakeEUR):'0,00 €';$('entryWindow').textContent=ready?`AHORA · hasta ${time(p.order.validUntil)}`:prepare?'ENTRA EN BOTEMANIA AHORA':'NO JUGAR';const remaining=ready?Math.max(0,Math.ceil((Date.parse(p.order.validUntil)-Date.now())/1000)):null;$('expiry').textContent=ready?`${remaining}s`:prepare?'≤ 2 min acceso':'—';$('instruction').textContent=ready?`CONFIRMA VERDE. ${g.name}: apuesta ${eur(p.order.stakePerSpinEUR)} por decisión, máximo ${p.order.maxSpins}. Si pasa a rojo, PARA.`:prepare?`ABRE BOTEMANIA, entra en ${g.name} y déjalo listo. NO apuestes hasta recibir JUGAR AHORA.`:'NO JUGAR. No realices ninguna apuesta.';const btn=$('playButton');btn.disabled=ph==='RED';btn.textContent=ready?'ABRIR JUEGO Y EJECUTAR':prepare?'ABRIR JUEGO · SOLO PREPARAR':'NO HAY SEÑAL PARA JUGAR';
  const struct=p?.evidence?.structurePass===true;$('structure').textContent=struct?'VALIDADA':'BLOQUEADA';$('structure').className=struct?'ok':'warn';const econ=p?.evidence?.economicPass===true;$('economy').textContent=econ?'VALIDADA':'BLOQUEADA';$('economy').className=econ?'ok':'bad';const persistedObserved=lane?.current?.observedAt||p?.coverage?.sourceObservedAt||l?.current?.observedAt||state.network?.observedAt||null;const direct=directRowForLane(lane);const age=direct?secAge(state.directAt):secAge(persistedObserved),freshLimit=Number(p?.order?.maxSignalAgeSeconds||180);$('freshness').textContent=age==null?'SIN DATO':`${age}s`;$('freshness').className=age!=null&&age<=freshLimit?'ok':age!=null&&age<=freshLimit*2?'warn':'bad';const candidateRtp=lane?.economic?.conservativeRtp??p?.evidence?.bestConservativeRtp??l?.current?.modelScreen?.bestConservativeRtp;$('rtp').textContent=rtpFmt(candidateRtp);$('observed').textContent=time(direct?state.directAt:persistedObserved);$('channel').textContent=(direct||(!lane?.monitor?.key&&directFresh()))?'DIRECTO':'EVIDENCIA';$('why').innerHTML=whyText();$('liveDot').style.background=ready?'var(--green)':prepare?'var(--amber)':'var(--red)';
}
async function refreshScientific(){const [plan,network,params,assets,metadata,live,validation]=await Promise.all([maybeJson(SOURCES.plan),maybeJson(SOURCES.network),maybeJson(SOURCES.params),maybeJson(SOURCES.assets),maybeJson(SOURCES.metadata),maybeJson(SOURCES.live),maybeJson(SOURCES.validation)]);state.plan=plan;state.network=network;state.params=params;state.assets=assets;state.metadata=metadata;state.live=live;state.validation=validation;render();}
async function directProbe(){try{const r=await fetch(BOT_GRAPHQL,{method:'POST',headers:{accept:'application/json','content-type':'application/json',venture:'botemania_es'},body:JSON.stringify({operationName:'loadJackpots',variables:{},query:BOT_QUERY}),cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=await r.json(),all=[];const add=(network,items)=>{for(const x of Array.isArray(items)?items:[]){const id=String(x?.id??'').trim(),amountEUR=Number(x?.amount);if(id&&Number.isFinite(amountEUR)&&amountEUR>=0)all.push({network,id,amountEUR});}};add('generic',b?.data?.jackpots);add('redTiger',b?.data?.redTigerJackpots);add('blueprint',b?.data?.blueprintJackpots);if(!all.length)throw new Error('No counters');const counts=new Map();for(const x of all){const k=`${x.network}:${x.id}`;counts.set(k,(counts.get(k)||0)+1);}state.directByKey=Object.fromEntries(all.filter(x=>counts.get(`${x.network}:${x.id}`)===1).map(x=>[`${x.network}:${x.id}`,x]));const jpk={JACKPOTKING:'JACKPOT_KING',JACKPOTKING_REGAL:'REGAL',JACKPOTKING_ROYAL:'ROYAL'},pots={};for(const x of all.filter(x=>x.network==='blueprint')){const k=jpk[x.id];if(k)pots[k]=x.amountEUR;}state.directPots=pots;state.directAt=new Date().toISOString();state.directOk=true;$('gameCard').classList.add('flash');setTimeout(()=>$('gameCard').classList.remove('flash'),520);render();}catch{state.directOk=false;render();}}
$('playButton').addEventListener('click',()=>{if(phase()!=='RED')window.open(currentGame().url,'_blank','noopener');});setInterval(()=>{$('clock').textContent=clock();render();},1000);setInterval(refreshScientific,5000);setInterval(directProbe,3000);$('clock').textContent=clock();refreshScientific();directProbe();
