(()=>{
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const eur=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'}),cp=t=>window.copyText?window.copyText(t):navigator.clipboard?.writeText(t);
  const gameNames={bonoloto:'Bonoloto',primitiva:'Primitiva',euromillones:'Euromillones',eurodreams:'EuroDreams',gordo:'El Gordo',quiniela:'Quiniela',quinigol:'Quinigol','loteria-nacional':'Lotería Nacional'};
  const SEEN='lotai_seen_proposals_v2',PLAYED='lotai_played_v2';
  const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const idFor=(e,g)=>`${g.gameId}|${g.targetDate}|${e.version||e.title||e.source}`;
  function madridDate(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t)?.value;return `${g('year')}-${g('month')}-${g('day')}`}
  function dateHuman(){return new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date()).toUpperCase()}
  function lineHTML(line,i,prefix){return `<div class="ticket"><div><div class="nums">${esc(line.display||line.copy)}</div><div class="meta">${esc(line.label||`Apuesta ${i+1}`)}${line.meta?` · ${esc(line.meta)}`:''}</div></div><button class="copybtn" data-copy="${prefix}-${i}">Copiar</button></div>`}
  function entryBody(e,g,prefix){const lines=e.lines||[],unit=e.unitCostEUR||((e.theoreticalCostEUR&&lines.length)?e.theoreticalCostEUR/lines.length:0),copyAll=lines.map(x=>x.copy).join('\n'),pid=idFor(e,g),played=!!read(PLAYED)[pid],money=e.realMoneyPass===true;
    return `<div class="row"><div><div class="name">${esc(e.title)}</div><span class="badge ${money?'ok':'shadow'}">${money?'CANDIDATA DINERO REAL':'PRUEBA PROSPECTIVA · NO APOSTAR'}</span></div><div style="text-align:right"><b>${eur(e.theoreticalCostEUR)}</b><div class="meta">${lines.length?`${lines.length} apuestas × ${eur(unit)}`:'coste teórico'}</div></div></div>${lines.length?`<div class="actions" style="margin-top:11px"><button class="copybtn primary" data-all="${prefix}">Copiar ${lines.length===1?'apuesta':`las ${lines.length} apuestas`}</button>${money?`<button class="playbtn ${played?'on':''}" data-play="${prefix}">${played?'✓ Jugada registrada':'Marcar como jugada'}</button>`:''}</div><div class="evidence">${lines.map((x,i)=>lineHTML(x,i,prefix)).join('')}</div>`:''}${e.pool?.length?`<div class="evidence"><b>Números base del modelo:</b> ${e.pool.join(' · ')}<div class="meta" style="margin-top:5px">Dato técnico. No es una apuesta y no tienes que copiarlo ni introducirlo en SELAE.</div></div>`:''}${e.purpose?`<div class="meta" style="margin-top:9px">${esc(e.purpose)}</div>`:''}<div class="evidence"><b>Decisión:</b> ${money?'candidata para revisión final antes de apostar':'NO JUGAR CON DINERO REAL · 0 € autorizados por el sistema'}.</div><span class="manifest-copy" data-text="${esc(copyAll)}" data-prefix="${prefix}" hidden></span>`}
  function bindEntry(e,g,prefix){const lines=e.lines||[];document.querySelectorAll(`[data-copy^="${prefix}-"]`).forEach(b=>{const i=Number(b.dataset.copy.slice(prefix.length+1));b.onclick=()=>cp(lines[i]?.copy||'')});const all=document.querySelector(`[data-all="${prefix}"]`);if(all)all.onclick=()=>cp(lines.map(x=>x.copy).join('\n'));const play=document.querySelector(`[data-play="${prefix}"]`);if(play)play.onclick=()=>togglePlayed(e,g,play)}
  function togglePlayed(e,g,btn){const p=read(PLAYED),id=idFor(e,g);if(p[id])delete p[id];else p[id]={gameId:g.gameId,targetDate:g.targetDate,title:e.title,version:e.version||null,cost:Number(e.theoreticalCostEUR||0),markedAt:new Date().toISOString()};write(PLAYED,p);btn.classList.toggle('on',!!p[id]);btn.textContent=p[id]?'✓ Jugada registrada':'Marcar como jugada';renderMoney();window.toast?.(p[id]?'Añadida a dinero real':'Quitada del dinero real')}
  function renderGame(g,idx){const alt=g.alternatives||[];return `<section class="card featured" id="game-${idx}"><div class="meta" style="font-weight:950;color:#0b8f58;margin-bottom:8px">${esc(gameNames[g.gameId]||g.gameId).toUpperCase()} · DECISIÓN ÚNICA DE HOY</div>${entryBody(g.primary,g,`g${idx}p`)}${alt.length?`<details><summary>Investigación secundaria (${alt.length}) · no jugar</summary><div class="altbox"><div class="warning"><b>No son apuestas adicionales.</b> Son modelos de comparación interna para medir cuál funciona mejor. No se suman, no se marcan como jugados y no forman parte de la decisión principal.</div>${alt.map((e,j)=>`<div style="margin:12px 0;opacity:.72"><div class="name">${esc(e.title)}</div><div class="meta">Referencia experimental · coste real autorizado: 0 €</div></div>`).join('')}</div></details>`:''}</section>`}
  function bindGames(games){games.forEach((g,i)=>bindEntry(g.primary,g,`g${i}p`))}
  function remember(games){const s=read(SEEN);for(const g of games){const e=g.primary,id=idFor(e,g);s[id]={id,gameId:g.gameId,targetDate:g.targetDate,title:e.title,version:e.version||null,cost:Number(e.theoreticalCostEUR||0),unitCostEUR:Number(e.unitCostEUR||0),lines:e.lines||[],pool:e.pool||null,seenAt:s[id]?.seenAt||new Date().toISOString()}}write(SEEN,s)}
  function renderMoney(){const p=Object.values(read(PLAYED)),total=p.reduce((a,x)=>a+Number(x.cost||0),0);$('realInvested').textContent=eur(total)}
  async function research(){try{const d=await fetch('../data/research/metapleno-research-registry.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;return r.json()}),s=d.summary||{};$('researchAttempts').textContent=Number(s.knownCandidateConfigurations||0).toLocaleString('es-ES');$('researchArtifacts').textContent=Number(s.artifacts||0).toLocaleString('es-ES');$('researchVersion').textContent=`Hasta ${d.version||('v'+(s.maxVersion||'?'))} · ${s.uniqueGameFamilies||0} familias`;$('validatedFulls').textContent=String(s.repeatFullSignalArtifacts||0)}catch{$('researchAttempts').textContent='—';$('researchArtifacts').textContent='—';$('researchMeta').textContent='Registro pendiente de actualización'}}
  async function gate(){try{const d=await fetch('../data/gates/real-money-status.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;return r.json()}),s=d.summary||{},approved=Number(s.approvedStakeTodayEUR||0);$('gate').innerHTML=`<div class="row"><div><div class="name">Decisión de dinero real</div><div class="meta">${approved>0?'Hay presupuesto candidato; debe coincidir con la propuesta principal y superar revisión final.':'Hoy el sistema no recomienda apostar dinero real.'}</div><span class="badge ${approved>0?'ok':'blocked'}">${approved>0?'REVISIÓN FINAL':'NO APOSTAR'}</span></div><div style="text-align:right"><div class="hitbig">${eur(approved)}</div><div class="meta">autorizado</div></div></div>`}catch{$('gate').innerHTML='<div class="meta">Gate no disponible: NO APOSTAR.</div>'}}
  const nums=s=>String(s||'').match(/\d+/g)?.map(Number)||[];
  function scoreAttempt(a,truth){const main=truth.result?.main||[],set=new Set(main.map(Number));let best=0;for(const l of a.lines||[]){const arr=nums(l.copy).slice(0,main.length);best=Math.max(best,arr.filter(n=>set.has(n)).length)}let poolHits=null;if(a.pool?.length)poolHits=a.pool.filter(n=>set.has(Number(n))).length;return{best,poolHits,total:main.length,winning:main}}
  async function archive(gameId,year){const r=await fetch(`../data/archive/${encodeURIComponent(gameId)}/${year}.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw 0;return r.json()}
  async function results(){const local=madridDate(),seen=Object.values(read(SEEN)).filter(x=>x.targetDate<local).sort((a,b)=>b.targetDate.localeCompare(a.targetDate)),played=read(PLAYED);if(!seen.length){$('attemptResults').innerHTML='<div class="empty">Aún no hay decisiones principales anteriores registradas en este dispositivo.</div>';return}const out=[],cache={};for(const a of seen.slice(0,18)){try{const y=a.targetDate.slice(0,4),k=a.gameId+y;if(!cache[k])cache[k]=await archive(a.gameId,y);const rec=(cache[k].records||[]).find(r=>r.drawDate===a.targetDate);if(!rec)continue;out.push({a,s:scoreAttempt(a,rec),played:!!played[a.id]})}catch{}}if(!out.length){$('attemptResults').innerHTML='<div class="empty">Las decisiones están registradas, pero sus resultados oficiales todavía no están disponibles.</div>';return}$('attemptResults').innerHTML=out.slice(0,8).map(({a,s,played})=>`<div class="historyrow"><div class="row"><div><div class="name">${esc(gameNames[a.gameId]||a.gameId)} · ${esc(a.targetDate)}</div><div class="meta">${esc(a.title)} · ${played?'JUGADA':'NO JUGADA'}</div></div><div style="text-align:right"><div class="hitbig">${s.best}/${s.total}</div><span class="badge ${s.best===s.total?'ok':'result'}">${s.best===s.total?'PLENO':'MEJOR APUESTA'}</span></div></div><div class="meta" style="margin-top:7px">Resultado: <b>${s.winning.join(' · ')}</b>${s.poolHits!=null?` · números base acertados: <b>${s.poolHits}/${s.total}</b>`:''}</div></div>`).join('')}
  async function run(){const local=madridDate();$('dateLabel').textContent=`HOY · ${dateHuman()}`;renderMoney();research();try{const d=await fetch('../data/ui/today-manifest.json?ts='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw 0;return r.json()});if(d.today!==local||d.strictToday!==true||d.staleFallbackAllowed!==false){$('freshLabel').textContent='SIN DATOS VIGENTES PARA HOY';$('todayGames').innerHTML=`<div class="empty"><b>No se muestran apuestas antiguas.</b><br>El manifiesto es ${esc(d.today||'desconocido')} y hoy en Madrid es ${local}.</div>`;return}const games=(d.games||[]).filter(g=>g.targetDate===local&&g.primary?.targetDate===local);$('freshLabel').textContent=`ACTUALIZADO ${new Intl.DateTimeFormat('es-ES',{timeZone:'Europe/Madrid',hour:'2-digit',minute:'2-digit'}).format(new Date(d.generatedAt))} · ${games.length} JUEGO${games.length===1?'':'S'}`;$('todayGames').innerHTML=games.length?games.map(renderGame).join(''):'<div class="empty"><b>Hoy no hay ninguna decisión vigente.</b><br>El sistema seguirá actualizando esta portada.</div>';remember(games);bindGames(games)}catch{$('freshLabel').textContent='ACTUALIZACIÓN PENDIENTE';$('todayGames').innerHTML='<div class="empty"><b>Resumen de hoy aún no disponible.</b><br>NO APOSTAR hasta disponer de una decisión vigente.</div>'}finally{gate();results()}}
  run();setInterval(run,5*60*1000);
})();